### ISSUE TITLE
This raise an error if user does not have sale groups

### ISSUE THREAD

**Issue by sergiocorato** [OCA/OCB#1004]
https://github.com/OCA/OCB/blob/44781b49c829a9883529cf2acff21d1e94fee773/addons/sale_stock/models/stock.py#L126

**Comment by pedrobaeza** [comment]
Is this something specific of OCB?

**Comment by sergiocorato** [comment]
I'll add this issue to Odoo too

**Comment by pedrobaeza** [comment]
In fact, it should only be in odoo/odoo. You can put here the PR after putting the proper one in Odoo. You should put more information on steps to reproduce the problem though if you want some attention from Odoo itself.

**Comment by sergiocorato** [comment]
moved to https://github.com/odoo/odoo/issues/68052
Thanks
