### ISSUE TITLE
Odoo - error of too many redirections in web browser - Too many redirects - please clear your cookies

### ISSUE THREAD

**Issue by Rai-Mohammed** [OCA/OCB#1014]
Impacted versions: Odoo 12 CE

Steps to reproduce: Usual installation of Odoo from OCA/OCB, Odoo OCA Web Responsive, Odoo OCA Progressive web application (PWA) and others Odoo OCA modules

Current behavior: Too many redirects - please clear your cookies errors

Expected behavior: Eliminates the error of "Too many redirects - please clear your cookies"

Description :
I installed Odoo 12.0 Community Edition from OCA/OCB, Odoo OCA Web Responsive, Odoo OCA Progressive web application and others Odoo OCA modules.

After many Login in the ERP and Logout, or profiling the execution with the developer tools from the browser, 
I get an error of too many redirections in web browser - "Too many redirects - please clear your cookies".

As you can see, the Odoo OCA /web_pwa_oca/manifest.webmanifest is accessible from the web browser. 

Do anyone have experienced this bug before and how to fix this error.
Below is the log access of the nginx web server and web browser profiling, showing the bug redirection.

Thanks for the help and all the best.

Video/Screenshot link (optional):

![Odoo error in web browser - so many redirects - please clear your cookies -  login web browser](https://user-images.githubusercontent.com/59764135/117572100-435cc380-b0c9-11eb-9e78-816f305aa014.png)
![Odoo error in web browser - so many redirects - please clear your cookies - when login](https://user-images.githubusercontent.com/59764135/117572110-51124900-b0c9-11eb-8f6b-69d44f50d335.png)
![Odoo error in web browser - so many redirects - please clear your cookies - when Network profile from the browser web_pwa_oca manifest-webmanifest](https://user-images.githubusercontent.com/59764135/117572126-5d96a180-b0c9-11eb-861e-da9269d8c0c2.png)
![Odoo error in web browser - so many redirects - please clear your cookies - when accessing web_pwa_oca manifest-webmanifest](https://user-images.githubusercontent.com/59764135/117572136-66877300-b0c9-11eb-9cd9-f46057f88700.png)
![Odoo error in web browser - so many redirects - please clear your cookies - when accessing from the browser web_pwa_oca manifest-webmanifest](https://user-images.githubusercontent.com/59764135/117572144-6ab39080-b0c9-11eb-871e-814750de7577.png)

![Odoo error in web browser - so many redirects - please clear your cookies -  console web browser](https://user-images.githubusercontent.com/59764135/117572616-9cc5f200-b0cb-11eb-99c9-83fbb6eba306.png)

**Comment by pedrobaeza** [comment]
This is not something specific of OCB, nor of Odoo itself, but a foreign instance thing. You should check the combination of code, third-party modules, deployment... and any doubt/problem of this thing should go to forums or mailing lists.

**Comment by Rai-Mohammed** [comment]
@pedrobaeza "This is not something specific of OCB, nor of Odoo itself, but a foreign instance thing".
The deployment it's an All-in-one VM, and I tested this many times by reinstalling the Odoo ERP from OCA/OCB, and use only modules that came from Odoo and OCB.
There is no third-party modules.

**Comment by nilshamerlinck** [comment]
Hi @Rai-Mohammed what Pedro means is that it's not directly related to OCB, probably more related to `web_pwa_oca`, so it would be better to open an issue in https://github.com/OCA/web :-) (where you could share your odoo/nginx config, because it probably has to do with `proxy_mode`)

**Comment by pedrobaeza** [comment]
Well, not only that, as the module `web_pwa_oca` is not the problem, but as you say, probably a bad reverse proxy configuration, so nothing to be handled at issue trackers' level.

**Comment by Rai-Mohammed** [comment]
HI @pedrobaeza @nilshamerlinck  This is my nginx_odoo_erp_odoo12ce_server config file, can you take a look if there is any error or mistake.
 The  proxy_mode = True in my odoo_config file.
https://docs.google.com/document/d/1wlDC2hIZ4-nPzt4qjFhtz1JMKoiJxa62sCn3IW2o0lY/edit

**Comment by Rai-Mohammed** [comment]
Hi @nilshamerlinck did you notice any errors or mistakes, from my Odoo Nginx configuration file.
and if the  error of "too many redirections in web browser - Too many redirects - please clear your cookies" is related to a wrong config.
