### ISSUE TITLE
[14.0]mail_debrand : when the word odoo only is present an url, it disappears 

### ISSUE THREAD

**Issue by flotho** [OCA/OCB#1016]
Impacted versions: v14

Steps to reproduce:
setup a web.url with odoo in it eg : 122456.odoo.tld.com
use survey and share a survey

Current behavior:
the url received has this as domain : 122456.tld.com

Expected behavior:
keep all the url : 122456.odoo.tld.com

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This doesn't belong here.

**Comment by flotho** [comment]
(facepalm) too many tabs

**Comment by cbssolutions** [comment]
you want debrand odoo, and you are setting your subdomain with odoo?

if you realy want it,change the line 

return re.sub("[^(<)(</)]odoo", "", value, flags=re.IGNORECASE)  

with 

return value
