### ISSUE TITLE
Point of Sale tax mapping broken when using taxes included in price and using specific tax regime.

### ISSUE THREAD

**Issue by blaskurain** [OCA/OCB#1020]
Impacted versions: 12.0

Steps to reproduce:
1. Initialize DB (English, USA).
2. Install Point of Sale app.
3. Create product TestProduct with Sales Price = 1 and Tax 15%
4. Ensure Tax 15% has "Included in Price" checked.
5. Create TestFiscalPosition fiscal position and leave it empty.
6. Ensure that Point of Sale configuration has TestFiscaPosition set as Fiscal Position / Use a default specific tax regime.
7. Create a new Point of Sale Session and click the TestProduct product.

Current behavior:
TestProduct shows $0.87 unit price. Total is $0.87 and Taxes $0.11

Expected behavior:
TestProduct shows $1.00 unit price. Total is $1.00 and Taxes $0.13

**Comment by blaskurain** [comment]
May I ask why this was closed? Also, the PR #1021 is still pending, not merged not rejected.

**Comment by pedrobaeza** [comment]
I have closed it because there's a PR about it. You shouldn't duplicate things: or an issue, or a PR, not both.

**Comment by blaskurain** [comment]
Thank you, I will take it into account in the future.
