### ISSUE TITLE
Odoo 14 Multi-tenant didn't work

### ISSUE THREAD

**Issue by messi655** [OCA/OCB#1027]
Impacted versions: Odoo 14

I have cloned Odoo 14 from https://github.com/odoo/odoo
And setup on my server (CentOS).
I want to setup Odoo multi-tenant:
with my architecture is: user ---> nginx ----> Odoo ----> Postgresql DB
I have created 3 databases: odoodb1, odoodb2, tintin

And I have configure file is odoo.conf

`
[options]

addons_path = /project/addons,/project/odoo/addons

admin_passwd = my password

data_dir = /project/Odoo

db_host = 127.0.0.1

db_maxconn = 64

db_password = db_password

db_port = False

db_sslmode = prefer

db_user = db_users

dbfilter = ^%d$

email_from = False

http_enable = True

http_interface = 127.0.0.1

http_port = 8069

proxy_mode = True

list_db = False

log_db = False

log_db_level = warning

log_handler = :INFO

log_level = info

logfile = /project/logs/digital.log

longpolling_port = 8072

max_cron_threads = 2

workers = 2
`
I started the Odoo service and nginx, postgresql they are work well
But when I access URL: odoodb1.mydomain.com or odoodb2.mydomain.com or tintin.mydomain.com
I alway redirect to https://{URL}/web/database/selector

But my expectation is https://{URL}/web/login base on the above URL

What I am wrong in configuration?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by messi655** [comment]
@pedrobaeza Yes,  I read and follow very carefull the guideline document above and I tried to deploy many time on my server but it did not work.

**Comment by pedrobaeza** [comment]
Then you should go to forums or mailing lists for further help.
