### ISSUE TITLE
[12.0] Text fields in product.template can't get blank when more than one language active

### ISSUE THREAD

**Issue by antonio-trey** [OCA/OCB#1040]
Impacted versions:

- 12.0

Steps to reproduce: 

- Activate another language in "Settings > Translations".
- Go to Products (product.template model) and select any one.
- Fill any text field, like "Internal Notes" for example.
- Save and edit again, remove any text in that field.
- Save, the first text written is now shown again.

Current behavior:

- Text fields cannot be blank once edited.

Expected behavior:

- Text field can be blank once edited.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This issue tracker is just for specific issues of OCB, not odoo/odoo ones.

Anyways, that's the intended behavior, and a workaround is to put an space.
