### ISSUE TITLE
NameError: name 'crypto' is not defined

### ISSUE THREAD

**Issue by thiagoblisboa** [OCA/OCB#1041]
Impacted versions:
v14
Steps to reproduce:
When I try to edit my company information the error comes out. 
Current behavior:
Erro odoo
Expected behavior:
Open the company page.
Video/Screenshot link (optional):
![erro odoo](https://user-images.githubusercontent.com/38355984/135197863-7625ee1f-41e9-4bd4-bd30-e8a4fc675236.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is not specific to OCB, so closing.

**Comment by CarlosEduardo96** [comment]
Checa crypto de la libreria OpenSSL que usa odoo, posiblemente te de problemas por la version de python.
