### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by copacarmine** [OCA/OCB#1046]
Missing "conf" file
![138683938-9d913a2e-8bc5-4e32-b2e4-e235fad0ef87](https://user-images.githubusercontent.com/59513546/139532802-376f2ac4-c1d3-4807-bbcf-48b8cd404ce8.png)

**Comment by pedrobaeza** [comment]
Bad deployment on your side.

**Comment by copacarmine** [comment]
@pedrobaeza Hi
Sorry to reopen the issue and sorry for the disturbance. I think I've solved the problem, once I run the command from the previous screenshot everything seems to be ok.
Once I reach my ip at port :8069 this appears to me, with no possibility to create database or anything else, does it always depend on my installation?

![errore2](https://user-images.githubusercontent.com/59513546/139537677-49331cea-4226-42ae-901a-0fba2105e8e3.png)

**Comment by pedrobaeza** [comment]
Please ask for help on forums. This is not the place for it.
