### ISSUE TITLE
Odoo v8: error installing account module in new databse

### ISSUE THREAD

**Issue by Bilbonet** [OCA/OCB#105]
I have this error installing "account" module in a new database with demo data:

ParseError: "ValidateError
Field(s) `date_stop` failed against a constraint: Error!
The period is invalid. Either some periods are overlapping or the period's dates are not matching the scope of the fiscal year." while parsing /home/odoo/estable/server/openerp/addons/account/demo/account_demo.xml:30, near
<record id="period_1" model="account.period">
            <field eval="'01/'+time.strftime('%Y')" name="code"/>
            <field eval="'X 01/'+time.strftime('%Y')" name="name"/>
            <field name="fiscalyear_id" ref="data_fiscalyear"/>
            <field eval="time.strftime('%Y')+'-01-01'" name="date_start"/>
            <field eval="time.strftime('%Y')+'-01-31'" name="date_stop"/>
            <field name="company_id" ref="base.main_company"/>
        </record>

**Comment by pedrobaeza** [comment]
Hi, Jesús, try updating sources, and if the problem persists the correct place to put the issue is in official branch (https://github.com/odoo/odoo). Only if the problem is specific to OCB branch, then you have to put it here.

**Comment by Bilbonet** [comment]
In a runboot with new database the same problem.
I will post the issue in a official branch.

Thanks Pedro.
