### ISSUE TITLE
No calculate correct volume and weight - posible solution - Odoo12

### ISSUE THREAD

**Issue by lparedesk** [OCA/OCB#1053]
https://github.com/OCA/OCB/blob/46c49ce4f6c9677463425981f01b69117c11943e/addons/pos_sale/report/sale_report.py#L57

Change with:

 (select sum(t.weight*l.qty/u.factor)) AS weight,
 (select sum(t.volume*l.qty/u.factor)) AS volume,

**Comment by pedrobaeza** [comment]
This is for notifying issues specific to OCB. For odoo/odoo ones, go to that repository.
