### ISSUE TITLE
Translation files do not appear for download in the translation wizard 

### ISSUE THREAD

**Issue by moval-agroingenieria** [OCA/OCB#1111]
When exporting a translation file (.po, .csv, .tgz) the file does not appear for download in the wizard.

## Module
OCB/web

## Describe the bug
When exporting a translation file (.po, .csv, .tgz) the file does not appear for download in the wizard.

## To Reproduce
**Affected versions**: 10.0

1. Go to /Configuration/Translations/Export traduction
2. Choose a format and export it
3. The file does not appears

**Expected behavior**
The file can be downloaded

**Additional context**
 It works if 'git reset --hard' to this commit: 700647cb5bbdfce34e9decadb08fd858dbb1250d

**Comment by pedrobaeza** [comment]
Please put the issue at odoo/odoo, not here.

**Comment by pedrobaeza** [comment]
I'm thinking that this may be due to the recent backports...

cc @simahawk @gurneyalex

**Comment by simahawk** [comment]
If I look at the last commits

![image](https://user-images.githubusercontent.com/347149/152174227-fa607aec-02c2-4916-930e-aa0c589eef6e.png)

my bet goes on [[FIX] web: more reliably avoid downloads on new file](https://github.com/OCA/OCB/commit/ea62945cc48dd045800c73bfe0d73e7cb42387a5) which is changing something on the download widget.

@moval-agroingenieria can you try restoring all commits but this one?

**Comment by moval-agroingenieria** [comment]
@simahawk, yes you are right, that commit is the one that introduces the error. We have simply done 'git reset --hard 700647cb5bbdfce34e9decadb08fd858dbb1250d', the the commit before this error.

And no, we have not tested to restore all commits except this one. We are waiting for the solution.

**Comment by i-vyshnevska** [comment]
issue related to https://github.com/odoo/odoo/commit/ea62945cc48dd045800c73bfe0d73e7cb42387a5
as a wizard doesn't save the file link is not shown

**Comment by simahawk** [comment]
> issue related to [odoo@ea62945](https://github.com/odoo/odoo/commit/ea62945cc48dd045800c73bfe0d73e7cb42387a5) as a wizard doesn't save the file link is not shown

That's what I linked above :wink:

**Comment by moval-agroingenieria** [comment]
At the moment, we have done an update and then we have reverted the changes introduced by [odoo@ea62945](https://github.com/odoo/odoo/commit/ea62945cc48dd045800c73bfe0d73e7cb42387a5). Everything seems to work again.

**Comment by pedrobaeza** [comment]
Please fix it or revert the patch on OCB branch

**Comment by i-vyshnevska** [comment]
I wanted to fix the issue for the patch https://github.com/OCA/OCB/pull/1106 but seems patch is not needed, 
as implementation for readonly/related rendering is different for v10 initial bug is not appears

**Comment by pedrobaeza** [comment]
I'm suffering the bug not seeing the link on a popup form not on edit mode

**Comment by gurneyalex** [comment]
I reverted the commit on 10.0
