### ISSUE TITLE
[13][BUG] website: Doesn't load menu when is a mobile/tablet and you are an user logged

### ISSUE THREAD

**Issue by igallart** [OCA/OCB#1121]
Version 13.0 community.

When you are using a mobile/tablet and you are an user logged, the main menu in website doesn't show the menus.
[website_menu_responsive.zip](https://github.com/odoo/odoo/files/8618665/website_menu_responsive.zip)

My approach would be:

https://github.com/puntsistemes/odoo/commit/aa81204f91ea7630f2dcae3f31e8d26d8adcf230

https://github.com/odoo/odoo/issues/90473

**Comment by pedrobaeza** [comment]
Can you put the PR instead?

**Comment by igallart** [comment]
https://github.com/OCA/OCB/pull/1122
