### ISSUE TITLE
Internal note is displayed on the invoice

### ISSUE THREAD

**Issue by cfrancoae** [OCA/OCB#1140]
## Module
Account

## Describe the bug
We have seen that the "Narration" field with the "Add an internal note" placeholder is displayed when printing the invoice for customers and suppliers.

## To Reproduce
**Affected versions**:
All versions

1. Edit an invoice
2. Add text to Narration field
3. Save invoice
4. Print invoice

**Expected behavior**
We understand that since we are talking about an internal note, it shouldn't be displayed on the invoice.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Please publish your issue in odoo/odoo, not here, as the problem you mention is not specific of this soft-fork.
