### ISSUE TITLE
To understand OCB, please, read the Wiki

### ISSUE THREAD

**Issue by zeroheure** [OCA/OCB#1145]
All of yours who need help with this project, [several wiki pages](https://github.com/OCA/OCB/wiki) explain it (and also [how to install](https://github.com/OCA/OCB/wiki/FAQ#how-to-use-ocb)). In short, OCB contains bugfixes. 

This is not a report. As we can't change the README, this issue help new users.

**Comment by pedrobaeza** [comment]
I have finally changed the README, so closing this.
