### ISSUE TITLE
[16][BUG] Point of sale _save_to_server undefined var error

### ISSUE THREAD

**Issue by alv97** [OCA/OCB#1156]
When error is provide by odoo backend, getting error.message.code but in the point_of_sale is checking error.code and this is undefined.
## Module
point_of_sale

## Describe the bug
catch method of [_save_to_server](https://github.com/OCA/OCB/blob/16.0/addons/point_of_sale/static/src/js/models.js#L797) is not executing because error.code not exist

## To Reproduce
**Affected versions**:
Force error on pos.order method create_from_ui, after that _save_to_server will get an error, that has and diferent structure.

1. Go to point of sale in v16, and try to create an order.
2. Force an error, on pos.order create_from_ui method
3. We see that error that backend provide is using diferent structure that POS is checking

**Expected behavior**
We expect _save_to_server method change condition to [check code error](https://github.com/OCA/OCB/blob/16.0/addons/point_of_sale/static/src/js/models.js#L837).

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
![image](https://user-images.githubusercontent.com/15813990/214813988-662b116c-3804-4e32-a944-c27c7aae4ef6.png)

**Comment by pedrobaeza** [comment]
This is not something exclusive of OCB, so you should put it on odoo/odoo instead.
