### ISSUE TITLE
[12.0][BUG] related to OpenUpgrade Issue3704

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/OCB#1157]
@pedrobaeza I really check no only odoo code but also OCB code and the code is the same that i posted here. https://github.com/OCA/OpenUpgrade/issues/3704

It really doesnt make sense that Oupgrade doesnt work because is a pretty standard view. 

Do you have any idea of what can it be?

**Comment by pedrobaeza** [comment]
For migrating from 12 to 13 you need v13, and as said, there's no such view in v13.
