### ISSUE TITLE
backport https://github.com/odoo/odoo/issues/111651  to Odoo 13.0

### ISSUE THREAD

**Issue by jeffery9** [OCA/OCB#1158]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by jeffery9** [comment]
https://github.com/odoo/odoo/issues/111651

**Comment by pedrobaeza** [comment]
I doubt that's possible due to all the framework changes, but if you want to try, put the pull request, but opening an issue here is not adding value IMO.
