### ISSUE TITLE
[15.0] Problem showing contact name field when switching between company and individual company type

### ISSUE THREAD

**Issue by forvas** [OCA/OCB#1160]
## Module
base.

## Describe the bug
When I create a new partner, it is set as a company by default. However, I see the placeholder _e.g. Brandom Freeman_, whereas I should be seeing the placeholder _e.g. Lumber Inc_. This means that the following code is not working properly:

```xml
<field name="company_type" widget="radio" options="{'horizontal': true}"/>
<h1>
    <field id="company" class="text-break" name="name" default_focus="1" placeholder="e.g. Lumber Inc" attrs="{'required' : [('type', '=', 'contact'),('is_company', '=', True)], 'invisible': [('is_company','=', False)]}"/>
    <field id="individual" class="text-break" name="name" default_focus="1" placeholder="e.g. Brandom Freeman" attrs="{'required' : [('type', '=', 'contact'), ('is_company', '=', False)], 'invisible': [('is_company','=', True)]}"/>
</h1>
```

## To Reproduce
**Affected versions**: 15.0 (at least).

1. Got to Contacts main menu.
2. Click on _Create_ button.
3. Check how `field id="company"` is never shown.

**Expected behavior**
It should be showing `field id="company"` when `company_type` is set as `company`.
It should be showing `field id="individual"` when `company_type` is set as `individual`.

**Additional context**
It seems to work when I work with the Odoo S.A. core instead of OCA's (but this is not checked yet, since I did not try both on the same server).

**Comment by pedrobaeza** [comment]
There's not something specific on OCB about this, so this problem should be posted on odoo/odoo instead. Probably is not reproducible on Odoo runbot if all modules are installed. Please check this.
