### ISSUE TITLE
[IMP 8.0] Support for defining addon_path in several lines

### ISSUE THREAD

**Issue by antespi** [OCA/OCB#119]
Impacted versions:
- 8.0

Steps to reproduce:
1. Define addons_path using ConfigParser syntax for several lines. For example

``` bash
root_path = /var/openerp/odoo
addons_path: /usr/lib/python2.7/dist-packages/openerp/addons,
             %(root_path)s/addons/,
             %(root_path)s/extras/
```
1. openerp/tools/config.py will parse adddons folder starting with '/\n'

Current behavior:

``` bash
openerp: addons paths: ['/var/openerp/.local/share/Odoo/addons/8.0', u'/var/openerp/master/addons', u'/\n/var/openerp/master/partner-contact', u'/\n/var/openerp/master/bank-statement-reconcile', u'/\n/var/openerp/master/account-payment', u'/\n/var/openerp/master/l10n-spain', u'/\n/var/openerp/master/extras', '/var/openerp/master/openerp/addons']
```

Expected behavior:

``` bash
openerp: addons paths: ['/var/openerp/.local/share/Odoo/addons/8.0', u'/var/openerp/master/addons', u'/var/openerp/master/partner-contact', u'/var/openerp/master/bank-statement-reconcile', u'/var/openerp/master/account-payment', u'/var/openerp/master/l10n-spain', u'/var/openerp/master/extras', '/var/openerp/master/openerp/addons']
```

**Comment by StefanRijnhart** [comment]
:+1:, thanks!

**Comment by pedrobaeza** [comment]
:+1:

**Comment by l-arnold** [comment]
Do I understand you can use this syntax in the openerp-server.conf file?

root_path = /var/openerp/odoo
addons_path: /usr/lib/python2.7/dist-packages/openerp/addons,
             %(root_path)s/addons/,
             %(root_path)s/extras/

More to the point, can you just put a comma at the end..
I am used to using a $ to find a variable like (root_path).  It seems a % and %(parenthesis) might work.

(why is the "s" there in  %(root_path)s/addons/, 

Seems like this be Program related to OCB however.  I am just looking for barebones Odoo right now.  (so many paths, hard to debug after a while)

I will study OCB.  Looks like a Base Builder.  Perhaps I can integrate.
If folks are interested, II have been building a ISO w/ Odoo/Connector/OCA various at

https://github.com/l-arnold/tkl-nomadic-odoo
ISO built at:  https://sourceforge.net/projects/tklnomadicodoo/files/
