### ISSUE TITLE
[FIX] base: postgres subprocess error when dumping database 

### ISSUE THREAD

**Issue by igallart** [OCA/OCB#1207]
Hello, there is an error in current versions of Odoo, from version 8 at least, although it does not occur in all of them. The issue arises when trying to create a zip with Postgres version 16. I have created a pull request in Odoo, and it has been applied in version 15, and presumably, they will apply it in versions 16 and 17. Could a cherry-pick be applied in OCB for earlier versions from 8 to 14?

The commit is https://github.com/odoo/odoo/commit/b68a0479b2cb58e30ce94a938ac25d86f3a2f68b

Thanks!

**Comment by pedrobaeza** [comment]
If retro-compatibility is assured, then why not?

**Comment by igallart** [comment]
It has finally been implemented in odoo/ocb 17-15.

ocb:17 https://github.com/OCA/OCB/commit/ca217195d7bc99a35f7f555e994cd1d8e7ae54cd
ocb:16 https://github.com/OCA/OCB/commit/946e97a8320bebf82d97c9bede1ba9fe68afc0c7
ocb:15 https://github.com/OCA/OCB/commit/b68a0479b2cb58e30ce94a938ac25d86f3a2f68b

**Comment by igallart** [comment]
@pedrobaeza, would you have to make a pull request for each one? Or can someone do cherry-pick? I don't know how to proceed for this repository. Thank you very much.

**Comment by pedrobaeza** [comment]
A pull request per branch should be done the same as the rest of the OCA repositories.

**Comment by igallart** [comment]
Hello, all done!

**Comment by igallart** [comment]
Hi @pedrobaeza , who is responsible for the merge of this repository? Thanks!

**Comment by pedrobaeza** [comment]
Well, any of the core maintainers, but reviews should be done as well.

I'm closing this issue, as the PRs are already done.
