### ISSUE TITLE
[product] name_search bug 

### ISSUE THREAD

**Issue by scigghia** [OCA/OCB#122]
same bug as here: https://bugs.launchpad.net/openobject-addons/+bug/1028287
with patch proposed

**Comment by StefanRijnhart** [comment]
I don't think the bug is valid. Instead, it looks like your code referenced in the Launchpad bug is wrong. args is supposed to be a valid domain. Your override makes it an invalid domain.

**Comment by scigghia** [comment]
here my code: https://github.com/andreacometa/alternative_codes/blob/7.0/product/product.py#L46
I need to pass these : args = ['|', ('alternative_code', operator, '%' + name + '%')] + args

**Comment by StefanRijnhart** [comment]
Closing this as the issue has been discussed on the related PR
