### ISSUE TITLE
Invoicing : the "round per line" method rounds the total of a line after multiplying the unit price by the quantity

### ISSUE THREAD

**Issue by LaetitiaElabore** [OCA/OCB#1221]
## Module
account

## Describe the bug
In a invoice line, add several quantity of the same product : the "round per line" method rounds the tax included price after multiplying the unit price by the quantity, instead of rounding the unit price with the tax and multilpying it with the purchased quantity

## To Reproduce
**Affected versions**: 12, 14, 16

1. In Settings > General Settings > Invoicing > Rounding method : Select "Round per Line" and save

2. Create a product "A" with unit price 3.60€ before tax and add a 5.5% tax to the product

3. Create a invoice, add a line with 1 unit of the product "A"
4. The total invoice VAT included is 3.80€ 

5. Create an another invoice, add a line with 10 units of the product "A"
6. The total invoice VAT included is 37.98€

7. Create an another invoice, add 10 lines of 1 unit of the product "A"
8. The total invoice VAT included is 38.00€

**Expected behavior**
The step 6 should give a VAT included total of 38.00€
When "round per line" method is selected, in a invoice line, the tax included unit price should be rounded first, and then being multiplyed by the quantity

**Comment by pedrobaeza** [comment]
Please put the issue in odoo/odoo, as this is not something specific of this soft-fork.
