### ISSUE TITLE
12.0 out of sync!

### ISSUE THREAD

**Issue by yajo** [OCA/OCB#1228]
Unexpectedly, 3 months ago, Odoo pushed a fix to 12.0 branch: https://github.com/odoo/odoo/commit/ba1ba88874e2ae9716e59ec199eb739d58c3f771

It's not in OCB 12.0.

**Comment by pedrobaeza** [comment]
@sbidoul you deactivated the branch sync for this version, isn't it?

**Comment by sbidoul** [comment]
Yes, it is [synchronizing from 14.0](https://github.com/OCA/maintainer-tools/blob/400ffa99242c8b225ab4d34de78721a68b292a61/tools/ocb-sync.sh#L11). The best is to sync manually in this case.

**Comment by pedrobaeza** [comment]
OK, done manually at https://github.com/OCA/OCB/commit/978b2cf5c9356317107c8018e5aa5d233ecd23bc

**Comment by yajo** [comment]
Thanks!
