### ISSUE TITLE
[17.0] web: onchange method unexpected behaviour 

### ISSUE THREAD

**Issue by yibudak** [OCA/OCB#1274]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

- Create a "store=True" and compute field on model.x
- Add Many2one relation between model.y and model.x
- Add One2many field on model.y's form view with one2many_list widget.
- Change "name" field of model.y

This steps cause recompute of the unrelated field (mentioned in step1) in model.x

Related PRs:
https://github.com/odoo/odoo/commit/39be91b48ec2a0aa037ca17f776689ce9f59b1cc (fields.py:L1200)
https://github.com/odoo/odoo/pull/119510/commits/ee5102ac5c3937c62ce666119b0dc903a98d6242 (web/models/models.py:L1102)

I've checked Migration to X guides in OCA but couldn't find any changes about store=True compute fields. Do you guys know something about it?

**Comment by yibudak** [comment]
@pedrobaeza @legalsylvain

**Comment by legalsylvain** [comment]
Hi. I don't understand why Im' pinged ! I don't use and don't work on OCB.

Question : could you provide the issue you opened in Odoo project ?

**Comment by yibudak** [comment]
Hi @legalsylvain,
I didn't open an issue in Odoo project. Sorry for the mention, I thought you would know something about it.

**Comment by legalsylvain** [comment]
>  I didn't open an issue in Odoo project.

Please do it first. 
The objective of OCB is to apply patches that has been refused in the core. But V17 is still maintained by Odoo SA Team.

**Comment by pedrobaeza** [comment]
As stated by Sylvain.
