### ISSUE TITLE
Create branch 8.0 and set as default, remove master

### ISSUE THREAD

**Issue by bwrsandman** [OCA/OCB#13]
- [x] Create branch 8.0
- [x] set as default
- [x] remove master

**Comment by pedrobaeza** [comment]
We should decide before synch strategy before making this move, don't you think?

**Comment by bwrsandman** [comment]
Odoo has an 8.0 branch,
https://github.com/odoo/odoo/tree/8.0
we should probably follow that.

**Comment by pedrobaeza** [comment]
Yeah, but people will think that this branch is already a 8.0 OCB branch (with OCB specific patches), which is still not correct. I prefer to let as is until we make the sync move. Let's try to accelerate the sync decision started on the mailing list, and then, make this.

Regards.

**Comment by dreispt** [comment]
I'm in favour of creating the 8.0 immediately, even if it doesn't have ant OBC specific changes.
This will allow us to correctly setup test configs on projects right away.
OCb changes to come can be merged as soon as they are reviewed, as usual.

**Comment by max3903** [comment]
:+1: for 8.0 branch

**Comment by bwrsandman** [comment]
We need an 8.0 branch as we now have travis tests testing on both ocb and odoo

**Comment by rvalyi** [comment]
:+1: for v8 branch even without OCB patches yet.
 @pedrobaeza in any case people using v8 right now would already make a mistake (it's still quite unstable after the API merge), so I don't think we would add a lot of confusion until we make the merge/rebase decision

**Comment by pedrobaeza** [comment]
OK, but let's accelerate the decision to let this usable, also for 7.0 branch.

Regards.

**Comment by pedrobaeza** [comment]
Hi, I have synced 8.0 branch against last Odoo 8.0, 8.0 OCB branch is now the default and I've removed master branch to not get confused.

Next step must be to start an automatic synchronization process for 7.0 and 8.0 branch. I'm now starting to know more about git, so I will contribute to the debate soon. @StefanRijnhart, have you made any advance in this topic?

Regards.
