### ISSUE TITLE
Qweb parsig errors not verbose enough

### ISSUE THREAD

**Issue by PCatinean** [OCA/OCB#137]
Also posted in odoo repository

Affected versions: 8.0

Current behavior:

When a rendering error occurs in Qweb reports the stack trace provided does not give any indication of the element it was trying to render nor the line it was encountered.

It also does not provide the rendering error as it would if raising an error just after self.render_element method call in ir_qweb.py

Expected Behavior:

A verbose stack track regarding the element that failed rendering in the xml report so the user can quickly identify it and apply a fix without flailing around

**Comment by pedrobaeza** [comment]
Do you have a PR solving this?

**Comment by PCatinean** [comment]
Wanted to confirm first, wasn't sure if I was missing something.Will try to whip something up

**Comment by PCatinean** [comment]
Linked PR #138

**Comment by StefanRijnhart** [comment]
Closing this as the linked PR is obsolete.
