### ISSUE TITLE
bug crm_lead Error: use_parent_address field  unknown

### ISSUE THREAD

**Issue by petrus-v** [OCA/OCB#157]
A new issue happen after we merged PR #151 when creating a new  lead:

Got it on V7. I guess we got the same on V8

This error is shown:

```
Error: Champ use_parent_address inconnu dans le domaine [["use_parent_address","=",true]]
```

In fact I'haven't notice when I made PR #151 that [crm_lead inherits](https://github.com/OCA/OCB/blob/7.0/addons/crm/crm_lead.py#L71) from [format_address class](https://github.com/OCA/OCB/blob/4823ae6c5c27b8a1b6a9877ac30f8557adc56a35/openerp/addons/base/res/res_partner.py#L36-L96)

`format_address` is a python class used to display differently the address in the form view depending the country of the connected user. It replace the xml definition on the fly.

As long as `use_parent_address` is not a valid field on crm_lead object, this is crash.

But if we remove the `attrs="{'readonly': [('use_parent_address','=',True)]}"/>` we are creating again the  issue [#3264](https://github.com/odoo/odoo/issues/3264).

I'haven't the good solution about this, A quick fix could be to remove the inheritance in crm_lead. what do you think about ?

**Comment by pedrobaeza** [comment]
I've already found the issue on 8.0 as you says. A possible fix is to inherit same method on crm.lead, and remove that attrs part.

**Comment by ccomb** [comment]
I'm trying to see if there is a way to conditionaly add the use_parent_address in the format_address, depending on the current object, instead of hardcoding it in the layouts

**Comment by ccomb** [comment]
Here is a PR: #159

(I've just realized there is a confusion between issue numbers of odoo and ocb, so the PR does not appear here. What is the correct way to do?)

**Comment by pedrobaeza** [comment]
You have to name it completely the PR, not only with #.

**Comment by ccomb** [comment]
and how do I correctly link to ocb in the # of the commit message?

**Comment by pedrobaeza** [comment]
Uhm, you've caught me. I think it can be #OCB/number
