### ISSUE TITLE
[8.0] sale.order onchange removes line state

### ISSUE THREAD

**Issue by jesusVMayor** [OCA/OCB#162]
**Sale order onchanges set the order line state to False when the line has a related field**
I've also placed this issue in the odoo repo. Seems a bug of the web module, but I can not find it.
Impacted versions:
- 8.0

Steps to reproduce:
1. create a module with a related field in sale.order.line and add it in the tree view.
   In my case related with product_id.qty_available
2. create a sale.order, create a new line
3. change the partner or another field with on change

The old_api function not receives the state of line:
'order_line': [[0,
                  False,
                  {'delay': 7,
                   'discount': 0,
                   'name': '[XXX] PROD',
                   'price_unit': 1,
                   'product_id': 21,
                   'product_packaging': False,
                   'product_uom': 1,
                   'product_uom_qty': 1,
                   'product_uos': False,
                   'product_uos_qty': 1,
                   'purchase_price': 50,
                   'reservation_ids': [],
                   'route_id': False,
                   'tax_id': [[6, False, [1]]],
                   'th_weight': 0}]],

**Comment by pedrobaeza** [comment]
It's an specific bug of OCB, or it happens also on upstream?

**Comment by jesusVMayor** [comment]
also occurs in upstream

**Comment by pedrobaeza** [comment]
You have to publish the issue there. Here you can propose a patch to solve it, referencing the upstream issue.
