### ISSUE TITLE
[8.0 backport from master] website_portal

### ISSUE THREAD

**Issue by lukebranch** [OCA/OCB#163]
Hi OCB,

I'd like to suggest/request an OCB backport for the website_portal module for 8.0 from this branch in odoo-dev:

https://github.com/odoo-dev/odoo/tree/master-website-portal-dbo
http://46210-master-website-portal-dbo-e223b1.runbot7.odoo.com/

There are a number of features specifically related to website_sale that would be very useful for both B2B and B2C situations where you do not want to provide access to the Odoo backend interface for your customers.

For example, this interface on the website frontend for portal users after login (click 'my account'):
<img src="https://cloud.githubusercontent.com/assets/2337666/6159948/92eacd0c-b297-11e4-8c3c-848122e7dc42.png"/>

I apologise in advance if this is not the correct place to post this type of request.

**Comment by lepistone** [comment]
Hi @lukebranch,

the OCB branches actually tracks very closely the corresponding odoo branches, with in addition fixes that have not been merged upstream.

So I think a big feature backport is really out of scope with OCB. It could be made into a separate module, and the module could be proposed into one of the OCA repositories http://odoo-community.org/page/List like for example https://github.com/OCA/e-commerce.

The actual work to do that could end up being huge, and probably not worth it, but that is just my opinion, you can try of course!

Best
