### ISSUE TITLE
product_uos_qty not located in parent view on updating database

### ISSUE THREAD

**Issue by cubells** [OCA/OCB#164]
I've got an error when try to update my database in a clean database:

2015-02-16 04:59:15,264 6985 INFO XXX openerp.modules.loading: loading sale_stock/sale_stock_view.xml
2015-02-16 04:59:15,434 6985 ERROR XXX openerp.addons.base.ir.ir_ui_view: El elemento 'xpath expr="//field[@name='order_line']/form//field[@name='product_uos_qty']"' no puede ser localizado en la vista padre

Error de contexto:
Vista `sale.order.form.sale.stock`
[view_id: 781, xml_id: sale_stock.view_order_form_inherit, model: sale.order, parent_id: 615]
2015-02-16 04:59:15,436 6985 CRITICAL XXX openerp.service.server: Failed to initialize database `XXX`.
Vista `sale.order.form.sale.stock`
[view_id: 781, xml_id: sale_stock.view_order_form_inherit, model: sale.order, parent_id: 615]" while parsing /home/cubells/projectes/git/odoo80/src/core/addons/sale_stock/sale_stock_view.xml:5, near
record id="view_order_form_inherit" model="ir.ui.view"
            field name="name">sale.order.form.sale.stock
            field name="model">sale.order
            field name="inherit_id" ref="sale.view_order_form"
            field name="arch" type="xml"
                data

The problem is located in sale_stock module, and the fix is this commit that I sent to an incorrect repository:

https://github.com/cubells/OCB/commit/6c8f11c4a36367f17ed36394bb8b3e4e8cc04a86

**Comment by pedrobaeza** [comment]
Is this something specific to OCB?

**Comment by cubells** [comment]
Not. It's a problem that odoo has too:

https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/sale_stock_view.xml#L49

**Comment by pedrobaeza** [comment]
You know then the procedure :wink: :
- Make an issue on Odoo.
- Propose a PR there.
- Propose the same patch here.
