### ISSUE TITLE
[BUG] image_resize_image_big function: Wrong size

### ISSUE THREAD

**Issue by chesucr** [OCA/OCB#174]
Inside the file image.py the function

```
 def image_resize_image_big(base64_source, size=(1204, 1024), ...
```

it should be

```
 def image_resize_image_big(base64_source, size=(1024, 1024), ...
```

**Comment by pedrobaeza** [comment]
Please fill the issue in https://github.com/odoo/odoo, and then, you can put here a PR resolving the issue.

**Comment by alejandrosantana** [comment]
@chesucr Can you close this issue?
As you already reported it on offical odoo project and I already made 2 PR following your solution.
