### ISSUE TITLE
record rules access error

### ISSUE THREAD

**Issue by RamiTHelal** [OCA/OCB#215]
Hi.
I tried to organize our company's warehouses and locations to the desired structure from our company's point of view to locations such that, (Input, Stock, Packing, and Output).
Then I defined a separate record rule for each location, to differentiate between each location moves and the others. Foe a while, everything was going well, but surprisingly, it get a strange error for the storekeeper ...

"AccessError
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: stock.move, Operation: read) "
From the first glance I expected that the record rule missed the read permission, but that was wrong. The record rules have the four permissions set!

Can anyone help?
Regards,

**Comment by pedrobaeza** [comment]
This is something that you have to publish on Odoo itself (https://github.com/odoo/odoo), not here, because this is not OCB specific.
