### ISSUE TITLE
UOM field missing in order lines form

### ISSUE THREAD

**Issue by maxhome1** [OCA/OCB#225]
When i create an order line in purchase of a product that miss in Werehouse i have the error:
The following fields are invalid: Product unit of measure.
The fields UOM missing in this view

**Comment by pedrobaeza** [comment]
Is this something specific to OCB? If not, please publish on Odoo, not here.

**Comment by maxhome1** [comment]
I don't know if it's specific of OCB or Odoo, I noticed that the error occurs with both OCB with Odoo.

**Comment by pedrobaeza** [comment]
Then it's something of Odoo that OCB has inherited. I close the issue here then.
