### ISSUE TITLE
[8.0] Fail to download attachment on message group

### ISSUE THREAD

**Issue by syci** [OCA/OCB#230]
When I receive a message with an attachment created a group , I can not download
The url is https://syci.es/mail/download_attachment?model=mail.message&id=1256&method=download_attachment&attachment_id=344

On message on mail system is ok, on Odoo fail the download

My configuration on Apache 2 is:

<VirtualHost syci.es:80>
   ServerName syci.es
   Redirect permanent / https://syci.es/
</VirtualHost>

<VirtualHost syci.es:443>

ServerName syci.es
SSLEngine on
SSLProxyEngine on

SSLCertificateFile /etc/apache2/ssl/rapidssl_syci.crt
SSLCertificateKeyFile /etc/apache2/ssl/rapidssl_syci.key
SSLCertificateChainFile /etc/apache2/ssl/rapidssl_intermediate.crt
KeepAliveTimeout 10
<Proxy *>
     Order deny,allow
     Allow from all
</Proxy>
ProxyPreserveHost On

ProxyPass /longpolling/ http://localhost:7004/longpolling/
ProxyPassReverse /longpolling/ http://localhost:7004/longpolling/
ProxyPass / http://localhost:8004/
ProxyPassReverse / http://127.0.0.1:8004/
ErrorLog ${APACHE_LOG_DIR}/odoo-wwwsyci.error.log
LogLevel warn
CustomLog ${APACHE_LOG_DIR}/odoo-wwwsyci.access.log combined
ServerSignature Off
</VirtualHost>

**Comment by rlizana** [comment]
Try to change the line 

```
ProxyPass / http://localhost:8004/
```

by this line

```
ProxyPass / http://localhost:8004/ nocanon
```

Note that [nocanon] may affect the security of your backend, as it removes the normal limited protection against URL-based attacks provided by the proxy. I guess that means to use it at your own risk.

[Apache Doc](http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass)

**Comment by syci** [comment]
Thank you, the configuration change is made . I keep trying , though 
some attachments keep getting error.

**Comment by syci** [comment]
Thank you, the configuration change is made . I keep trying , though 
some attachments keep getting error.

**Comment by pedrobaeza** [comment]
Is this spec
