### ISSUE TITLE
mrp_operations.py calculate the End date of Work Orders wrongly

### ISSUE THREAD

**Issue by ghost** [OCA/OCB#237]
**"End date" (date_planned_end) of Work Orders is calculated wrong**

Impacted versions:
- 8.0, 7.0

Steps to reproduce:
1. go to Manufacturing in https://demo1.odoo.com/
2. create a new Manufacturing Order of "[HDD-DEM] HDD on Demand"
3. go to their Work Orders
4. watch the field "End date"

Current behavior:

![image](https://cloud.githubusercontent.com/assets/8233008/7187199/41afa7c8-e46f-11e4-818b-6d3aa5ccdb6d.png)

This is the code of this field in "mrp_operations" module:

```
       'date_planned_end': fields.function(_get_date_end, string='End Date', type='datetime'),
```

It seems that the function _get_date_end forget minutes and seconds of "Scheduled date".

Expected behavior:

The "End date" must be an addition of: "Scheduled date" + "Number of hours"

I reported this issue to Odoo on 16/04/2015 but I have not had any answer: https://github.com/odoo/odoo/issues/6348

**Comment by pedrobaeza** [comment]
Reporting this issue here doesn't mean anything. OCB is only intended for proposing patches fixing things, not for reporting again an Odoo issue.

Only issues affecting explicitly to OCB should be reported here.
