### ISSUE TITLE
Directory by resource is not working

### ISSUE THREAD

**Issue by ovnicraft** [OCA/OCB#26]
In 7.0 latest revno, install document and account modules.

Document module comes with some directorie configured by resource i use Partner directory.

Go to partners print, print overdue payments file is not attached (i did not expect that)
But i attach a file to my partner, file is uploaded but its directory is Documents not Partner's name.

I reported before but never fixed on 7.0.

**Comment by clonedagain** [comment]
Is that a regression introduced by OCB?

**Comment by ovnicraft** [comment]
No, its a bug present on addons and ocb and was confirmed a year ago, apparently fixed on 8.0 (not confirmed).
My report on LP https://bugs.launchpad.net/openobject-addons/+bug/1095339

**Comment by ovnicraft** [comment]
@clonedagain and patch reported does not works.

**Comment by bwrsandman** [comment]
What is the status on this?

**Comment by ovnicraft** [comment]
@bwrsandman nothing :(

**Comment by StefanRijnhart** [comment]
@ovnicraft, we don't track general Odoo issues on OCB, only pull requests. Are you planning to make one?
