### ISSUE TITLE
Missing commit from lauchpad OCB 7.0 branch in Github OCB 8.0

### ISSUE THREAD

**Issue by Garamotte** [OCA/OCB#274]
It seems that some commits from the launchpad OCB branch are not available on Github.
I was looking for this commit : http://bazaar.launchpad.net/~ocb/ocb-server/7.0/revision/4923

Is this a Launchpad to Github migration issue ? Or custom patches were abandonned when migrating to Github ?
I can make a pull request, if needed.

**Comment by eLBati** [comment]
But the code contains the change:
https://github.com/OCA/OCB/blob/7.0/openerp/addons/base/res/res_lang.py#L160

**Comment by Garamotte** [comment]
I searched in v8.0 code (where the change is not), and in commits, but I forgot to look the v7.0 code.
Thanks for pointing this out :)

How can this change be applied on v8.0 ?

**Comment by Garamotte** [comment]
My question was more "What's the best way to port a 7.0 change into 8.0 branch" :)

I've created PR #278

**Comment by eLBati** [comment]
Ah, in this case you could [cherry pick](http://git-scm.com/docs/git-cherry-pick) it

**Comment by eLBati** [comment]
Actually, you could not, because it was included in a super commit https://github.com/OCA/OCB/commit/409000dc23d385ddae874b5eb04b2d37deeef4e7

**Comment by Garamotte** [comment]
I saw that super commit, that's why I did a little commit instead.
I didn't check if other parts of this big commit have to be added in v8.0 or not.

**Comment by StefanRijnhart** [comment]
The PR has long since been merged, so I'm closing this issue. Thanks for the PR!
