### ISSUE TITLE
Mail alias is case sensitive

### ISSUE THREAD

**Issue by ghost** [OCA/OCB#298]
Hey!
This bug already exist in the official odoo github repository, but there has no be solution yet (is is open since a year)
https://github.com/odoo/odoo/issues/334

The Problem is that the mail alias is case sensitive so if I use the alias: [application@tttt.com] - [Application@ttt.com] wont work. Has somebody a solution or a hint?

Regards

**Comment by pedrobaeza** [comment]
Propose your solution then and make a PR against this branch. It's good to know that this issue exists, and maybe someone in the community decides to solve it, but take into account that this is not a free maintenance service.

**Comment by ghost** [comment]
This is a bug report. And if I could solve it,  then I would do it.  I had
done it many times.  Mostly in the help forums.  But this one I can't solve
by myself and I think the bug is critical,  this is why I post it again on
you repository.

Regards
Am 31.07.2015 14:12 schrieb "Pedro M. Baeza" notifications@github.com:

**Comment by StefanRijnhart** [comment]
Closing as per project target. We don't track Odoo bugs if no patch is provided by the submitter.

**Comment by mvaled** [comment]
Hi @pedrobaeza, @StefanRijnhart 

There's some activity around this issue that may be included in OCB.  I created a patch to fix this behavior, though it probably won't be accepted into the official 8.0 or 9.0 branches, OCB may actually use it.

Best regards,
Manuel.
