### ISSUE TITLE
bad directories: addonsmrp and addonsstock

### ISSUE THREAD

**Issue by rvalyi** [OCA/OCB#30]
Hello OCB folks,

take a look at these 2 directories addonsmrp and addonsstock here https://github.com/OCA/OCB/tree/7.0
it looks like a defect in the Launchpad porting script. Any idea? How to clean that?

cc @StefanRijnhart

**Comment by pedrobaeza** [comment]
Yeah, I see. It comes from this revision: f1295f158723fe72cac7b298b827f9f1dfd5c6ea, and it points to LP bug: https://bugs.launchpad.net/ocb-addons/+bug/1088412, but the revision that solves it it's simpler: http://bazaar.launchpad.net/~ocb/ocb-addons/7.0/revision/9274. The revisions that introduce this change are: http://bazaar.launchpad.net/~ocb/ocb-addons/7.0/revision/9211 and http://bazaar.launchpad.net/~ocb/ocb-addons/7.0/revision/9425. I will make a PR to order these changes.

Thanks for noticing.

Regards.

**Comment by pedrobaeza** [comment]
Here it is the PR that solves it: https://github.com/OCA/OCB/pull/31

**Comment by clonedagain** [comment]
PR is merged, this should be closed I guess.
