### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by hbrunn** [OCA/OCB#324]
Wouldn't it be a good idea to have the $version branches protected on OCA repositories? https://help.github.com/articles/about-protected-branches/

I was not aware github can do this, I only got to know it in gitlab and love it. Maybe it's a rather newish github feature?

**Comment by sbidoul** [comment]
It's a apparently a new feature indeed. 

:+1:

**Comment by dreispt** [comment]
Isn't it sometimes necessary to do a force push? I know it happened in the past, but I'm not sure why. @StefanRijnhart

**Comment by hbrunn** [comment]
I know it happened in the past as a mistake. If really necessary, an admin can unprotect the branch, do the push, protect again.

**Comment by StefanRijnhart** [comment]
:+1: A forced push in the past was only necessary after someone pushed their local changes by accident, AFAIK. If the admin can unprotect before doing that, perfect.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by legalsylvain** [comment]
:+1: Interesting indeed.

**Comment by clonedagain** [comment]
:+1: the repos are popular enough that no push can be undone now: someone will have pulled before you can undo the push anyway.

**Comment by tafaRU** [comment]
:+1:

**Comment by hbrunn** [comment]
I turned that on now for OCB, but didn't make a successful status from CI mandatory

**Comment by max3903** [comment]
Does it allow transbot to push the translations ?

**Comment by hbrunn** [comment]
good question, we'll see

**Comment by dreispt** [comment]
AFAICT only forced pushes are blocked. Does Transbot use `push -f`?

**Comment by max3903** [comment]
No
https://github.com/OCA/maintainer-tools/blob/master/tools/tx_pull.py#L284
