### ISSUE TITLE
PR #5620 from lmignon has not been merged

### ISSUE THREAD

**Issue by antespi** [OCA/OCB#332]
I've realized that PR https://github.com/odoo/odoo/pull/5620 from @lmignon was not really merged to OCB.

You can compare the commit: https://github.com/OCA/OCB/commit/e7e42ca605f6a3a272684a19c2ce178f89eeb520
With the actual `openerp/models.py` code: https://github.com/OCA/OCB/blob/8.0/openerp/models.py#L4183

Althought blame is telling other thing: https://github.com/OCA/OCB/blame/e7e42ca605f6a3a272684a19c2ce178f89eeb520/openerp/models.py#L4173

I've tested to clone 8.0 branch locally and @lmignon fix is not there.

Weird, isn't it?

**Comment by pedrobaeza** [comment]
Maybe some synchronization issue. Can you please propose again the same patch against OCB?

**Comment by antespi** [comment]
It has been fixed by itself. One weird thing + One weird thing = Some kind of magic
So I close this issue :smile:

**Comment by StefanRijnhart** [comment]
That would have been https://github.com/OCA/OCB/pull/350
