### ISSUE TITLE
9.0 as default

### ISSUE THREAD

**Issue by hbrunn** [OCA/OCB#333]
I just cloned 9.0 and pushed it to this repo too. Also updated the synchronization script in https://github.com/OCA/maintainer-tools/pull/136 - should we make 9.0 the default branch here?

**Comment by pedrobaeza** [comment]
Let's wait until 9.0 is official. Then I agree to put it as default.

**Comment by dreispt** [comment]
Already done.

**Comment by rvalyi** [comment]
@dreispt @pedrobaeza is it normal to have a .travis.yml in v8 and not in v9?
such as https://github.com/OCA/OCB/blob/8.0/.travis.yml

I think that would be interesting to know test coverage results in OCB v9, specially to know what is tested in Odoo and what is not.

**Comment by pedrobaeza** [comment]
As OCB requires a custom Travis file (OCA standard one doesn't serve), this have to be prepared specifically. @hbrunn made the previous one, so he can be the best bet to create the new one.

**Comment by dreispt** [comment]
OCB 9.0 was forked from Odoo and not from OCB 8.0, so it doesn't come with a .travis.yml.
It needs to be added.
