### ISSUE TITLE
[8.0][BUG] Missing Company when buying an Event

### ISSUE THREAD

**Issue by rafaelbn** [OCA/OCB#372]
I opened upstream https://github.com/odoo/odoo/issues/9508 but maybe we must fix this in OCB

**Comment by yvaucher** [comment]
@rafaelbn We only need to make bug reports on odoo/odoo no need to create an issue on OCB unless it is due to a patch only existing on OCB.

Only the PR must be present both on OCB and official branch.

**Comment by rafaelbn** [comment]
OK, thank for info!

**Comment by yvaucher** [comment]
Thanks for taking the time to report it anyway :wink:
