### ISSUE TITLE
[8.0][regression]  error: Scheduled Date 

### ISSUE THREAD

**Issue by JMODaERP** [OCA/OCB#374]
- Create company with logistics dates as following:
  
   Purchase Lead Time     3.00 
   Manufacturing Lead Time    7.00 
   Security Days  1.00 
- Create product with Customer Lead Time 20 days and  route in Supply Chain Information like as   following:
  
     Manufacture  Yes
     Make To Order Yes
- Create sale order with Requested Date **12/02/2015**.
- Confirm sale order.

Manufacturing Order is automatically created with Scheduled Date 11/23/2015.
- **Current behavior**
       Manufacturing Order auto created with Scheduled Date :**11/23/2015**.
- **Expected behavior**
      Manufacturing Order auto created should be Scheduled Date: **12/02/2015 – 20 days = 11/13/2015. (Requested Date  -   Customer Lead Time = Scheduled Date).

**Comment by dreispt** [comment]
Did you report this to Odoo?

**Comment by JMODaERP** [comment]
Yes, this report is to Odoo, OCA/OCB. In Odoo Core the current behavior and  the expected behavior are the same. Why, here no?.

**Comment by pedrobaeza** [comment]
José Manuel, this is call a "regression", which means that something that works on Odoo doesn't work on OCB, and thus the only place where put this is here. Please mark the issue with this word instead of BUG.

**Comment by JMODaERP** [comment]
Well, i´m sorry,  please tell me how can i solve the following problem:  the sale order has a determined  RequestedDate, required by customer,  and my productive system needs to be planned, so I have tell to production manager when must begin the production. 

My product says that are necessary twenty days for manufacture this product, what would the schedule date. I would thank you some  idea about this theme.

**Comment by pedrobaeza** [comment]
Please don't mix things. This is a regression report that I have put it on the name. What you are asking is a functional doubt and this issue tracker is not intended for that.

**Comment by JMODaERP** [comment]
cc @rafaelbn

**Comment by pedrobaeza** [comment]
Closing as no more news.
