### ISSUE TITLE
odoo v8 does not close user sessions when server is being shut down

### ISSUE THREAD

**Issue by dulhaver** [OCA/OCB#38]
odoo v8  server does not end user session when the server is being shutdown

**_Impacted versions:**_

github.com/OCA/OCB branch 8.0

**_Steps to reproduce:**_
1. login to your database
2. shutdown the odoo server
3. restart odoo server
4. browse to ip-address:8069

**_Current behavior:**_
- you will see that you are still logged in to your odoo database
- same behavior even happens when the OS of the odoo server has been shutdown

**_Expected behavior:**_
- odoo requires username/pw to login again. I think this should even happen when your usersession is inactive for a while

**Comment by dulhaver** [comment]
got a comment on the odoo-helpforum that said 'eternal' Session behavior was a feature by design in v6 at least. is it in v8 the same?

**Comment by pedrobaeza** [comment]
Yes, it is. BTW, you must publish issue in odoo official repository, not in OCB one.

Regards.
