### ISSUE TITLE
08 [IMP] Análisis de Costes

### ISSUE THREAD

**Issue by JMODaERP** [OCA/OCB#380]
Improvement: Ya que los seguidores pueden ver traducido al inglés esta mejora y para evitar una mala transimisión del improvement lo voy a escribir en castellano.

La estrategia del 85% de las empresas del tejido productivo español es la estrategia en costes. Es por ello que aquellas empresas que fabrican lo que venden y que tienen siempre presente aportar el máximo valor a sus inversores, y por ende,  aportando  más valor a sus clientes que sus competidores pongan gran énfasis en el análisis de costes de producción.

Creo que desde Odoo deberíamos darle mayor a la herramienta incorporando en el MRP el siguiente análisis:

**Menú ==> Informes ==> Producción ==> Análisis de Costes Reales.**

Cálculo de costes reales: para Análisis de Costes Reales.

a. Coste de materiales: Número de unidades, de materias primas consumidas producidas (product.qty del objeto mrp.production.product.line) por el Precio de Coste de cada la materia/s prima/s (cost_price del objeto product.product, en la pestaña de abastecimientos de la ficha del producto materia prima). 

Coste de Materiales = ∑ Materiali (product.qty del objeto mrp.production.product.line)*Precio de Costei (cost_price del objeto product.product); Siendo i = 1… n (cada una de las líneas de materiales consumidos).

b. Cálculo de las horas de producción real en función del inicio/paro de una orden de trabajo. 
Una vez creada una orden de trabajo, bien por haber pinchado el botón Calcular datos o bien al Confirmar la orden de producción se crean tantas órdenes de trabajo como operaciones se hayan incluido en la ruta. 

El responsable de producción o el operario responsabilizado marca los inicios y los paros del trabajo que sea realiza en el centro de trabajo , mediante los botones; Iniciada, Finalizada, Pendiente del objeto mrp.production.workcenter.line . 

El total horas de producción en el centro será la suma de los intervalos de producción real: ∑hfi-hii, para todo i = al número de intervalos (marcha/paro), siendo hii la hora de inicio y hfi la hora de paro o fin del intervalo. 

c. Coste de máquina: Cuando medimos en horas: es el Precio de Coste del producto determinado en Producto centro de producción (product_id del objeto mrp.wokcenter), colocado en el Coste horas (cost_hour del objeto mrp.wokcenter), por las horas calculadas en b. 

Será igual al (cost_cycle del objeto mrp_wokcenter) por los ciclos realizados, cuando medimos en ciclos número de ciclos es igual a la cantidad fabricada dividido entre la capacidad del ciclo definida en la línea CT de la ruta (opc_wc_lines del objeto mrp.routing.workcenter/capacity_per_cycle). 

d. Costes de operarios. Se compone de la suma de: 

1.- Precio medio determinado en la pestaña Operarios (op_avg_cost del objeto mrp.workcenter) por la suma de las horas realizadas por cada operario. Horas imputadas que se reflejarán en una nueva pestaña “tareas” (de proyecto) en la orden de trabajo .

2.- Precio del producto de coste de pre-operación, pre_op_product del objeto mrp.workcenter, (cost_price del objeto product.product) por las horas de pre-producción (time_start de la línea de CT de la orden, tiempo antes de prod). 

3.- Precio del producto de coste de post-operación, post_op_product del objeto mrp.workcenter, (cost_price del objeto product.product, precio de coste variante) por las horas de post-producción (time_stop de la línea de CT, tiempo después de prod).

**Comment by pedrobaeza** [comment]
José Manuel, this is not related to here, and less in spanish. I close.
