### ISSUE TITLE
[7.0][OCB Specific] account_aged_partner_balance.py

### ISSUE THREAD

**Issue by gdgellatly** [OCA/OCB#388]
@StefanRijnhart 
In commit  https://github.com/OCA/OCB/commit/797ea419d2fde54d8532a27734b15a284c6d84ba a fix was introduced "Aged partner balance unreconciled amount selection off by one day".  Unfortunately the fix is not timezone aware and so I think it creates/illuminates the reverse problem of what it sought to solve. 

I'm not sure what the solution is here but imagine it involves changing that line to be basically recon.create_date > date_field::timestamp - user_tz difference + 1 day, but as I say I don't know.  Does that seem right, or does it need to be in the user who created the entries timezone?  Official gives me correct result, OCB has a difference between General Ledger and Aged Partner Balance report.

**Comment by StefanRijnhart** [comment]
Hi @gdgellatly. See https://bugs.launchpad.net/openobject-addons/+bug/1210524. As I am living and working in GMT+1 it is very well possible that I introduced timezone issues that I was not aware of. Sorry to cause you any trouble. The bug description seems valid enough, so we would need to come up with a better solution.

**Comment by gdgellatly** [comment]
Hi Stefan,

I looked more at it.  The bug report was closer than the solution.  Pretty
much the timestamp argument should be > reportdate:23:59:59 - user_tz.
This works fine if the user is in the same timezone as the person who
created the reconciliation, however really the solution needs to be a naive
date field stored in the original users timezone which is outside OCB scope
so will just fix myself.  The reason for this is fairly straightforward.

When creating a customer payment and reconciling (I am GMT+13) on the first
day of a financial year, the aged partner balance needs to add up to the
general ledger total.  (Actually they should be the same on any day) As it
stands it won't.  It will exclude the past entry reconciled on the first
day (in my case before 1pm, in yours before 1am) leading to an imbalance.

**Comment by pedrobaeza** [comment]
Closing as no further news and very old version.
