### ISSUE TITLE
[7.0][account] Bank statement wrong currency

### ISSUE THREAD

**Issue by kenvac** [OCA/OCB#39]
Hi,

The bank statement currency is taking user company currency which is wrong. Ideally it should take currency from journal.

The following patch worked for me

``` python
=== modified file 'account/account_bank_statement.py'
--- account/account_bank_statement.py   2014-08-14 15:13:25 +0000
+++ account/account_bank_statement.py   2014-08-21 12:08:48 +0000
@@ -70,13 +70,13 @@
     def _currency(self, cursor, user, ids, name, args, context=None):
         res = {}
         res_currency_obj = self.pool.get('res.currency')
-        res_users_obj = self.pool.get('res.users')
-        default_currency = res_users_obj.browse(cursor, user,
-                user, context=context).company_id.currency_id
+        #res_users_obj = self.pool.get('res.users')
+        #default_currency = res_users_obj.browse(cursor, user,
+                #user, context=context).company_id.currency_id
         for statement in self.browse(cursor, user, ids, context=context):
-            currency = statement.journal_id.currency
-            if not currency:
-                currency = default_currency
+            currency = statement.journal_id.currency or statement.journal_id.company_id.currency_id
+            #if not currency:
+                #currency = default_currency
             res[statement.id] = currency.id
         currency_names = {}
         for currency_id, currency_name in res_currency_obj.name_get(cursor,
```

[Steps to reproduce Bug]
- Create or import bank statement with currency different than base currency. (Set currency on Journal)
- The currency symbol shows logged in user currency instead of journal currency. 

Let me know if more information is needed. 

Regards,
K

**Comment by pedrobaeza** [comment]
Hi, @kenvac, if this error is also reproducible on upstream branch (the official one), you should report to it first, and then make a PR here with the corresponding patch.

Regards.

**Comment by StefanRijnhart** [comment]
Hi @kenvac, we only track OCB regressions as issues. Can you confirm that this is either an OCB regression or an Odoo specific issue (in which case you should file an issue against Odoo and close this one). You may open a pull request though, against both Odoo and OCB.

**Comment by kenvac** [comment]
Hi StefanRijnhart,
i can confirm the regression is in ocb. 

Regards,
kinner

**Comment by StefanRijnhart** [comment]
@kenvac The file that you point out containing the flaw does not contain any ocb-specific changes in 7.0. Are we talking about the same thing? When I say 'regression in OCB', I mean that the problem does not occur in vanilla Odoo but is introduced by an OCB specific bugfix. That also means that we should be able to identify the change responsible for the regression.  Of course, it is always possible that the change is in a different file but please confirm that the same problem does not occur in plain Odoo.

**Comment by StefanRijnhart** [comment]
Closing after more than a year without activity.
