### ISSUE TITLE
[9.0 - hr_attendance] wrong calculation difference between 2 datetime if worked hours > 24

### ISSUE THREAD

**Issue by cvinh** [OCA/OCB#411]
if worked hours > 24h, calculation is wrong because "seconds" funtion does not take into account days

total_seconds() should be used instead of seconds function

**Comment by cvinh** [comment]
fix in PR 410

issue also registered to odoo/odoohttps://github.com/odoo/odoo/issues/10381
PR also proposed to odoo/odoo : https://github.com/odoo/odoo/pull/10382

**Comment by StefanRijnhart** [comment]
Please don't create issues on OCB or even Odoo if you propose a PR as well.
