### ISSUE TITLE
[8.0][9.0] tree views do not keep group_by expanded

### ISSUE THREAD

**Issue by cvinh** [OCA/OCB#415]
ref : https://github.com/odoo/odoo/issues/10428

Steps to reproduce :

open a tree view
choose a group_by
expand the list with one or several groups
open a record in form view
return to the list (list button on top-right or the breadcrumb on top-left)
the tree view is all collapsed
Wished behavior :

when returning in tree view, we should keep the previously expanded groups expanded

**Comment by StefanRijnhart** [comment]
Closing this as we only track issues that are OCB specific.
