### ISSUE TITLE
[9.0] uncheck "expand all" button does not work in pivot view

### ISSUE THREAD

**Issue by cvinh** [OCA/OCB#416]
ref : https://github.com/odoo/odoo/issues/10427

In Pivot view, the expand all button works well. But when we unclick the button, nothing happens

The correct behavior would be : when we unclick the expand all button, we should have a collapse all action

or better : we should return to previous state (before the button was clicked)

**Comment by StefanRijnhart** [comment]
Not specific to OCB, I suppose?
