### ISSUE TITLE
[9.0-web] pivot views do not support widgets

### ISSUE THREAD

**Issue by cvinh** [OCA/OCB#420]
widgets on measure fields are not supported
See https://github.com/odoo/odoo/issues/10473

**Comment by cvinh** [comment]
fixed in https://github.com/OCA/OCB/pull/421
to test it, you can add widget=float_time in hr_attendance pivot view measure fields

**Comment by cvinh** [comment]
Odoo SA has merged it in master https://github.com/odoo/odoo/pull/10474 not in v9

**Comment by pedrobaeza** [comment]
Closing issue, as OCB only tracks PRs
