### ISSUE TITLE
[7.0] [account_asset] Declaration of method action_number

### ISSUE THREAD

**Issue by hugosantosred** [OCA/OCB#46]
In account_asset the inherited method action_number from account.invoice is declared as shown in https://github.com/OCA/OCB/blob/7.0/addons/account_asset/account_asset_invoice.py#L27 using _args without context or *_kwargs

So if you call that method from another place with that addon installed and using context=context you'll get an exception because that inherited method don't have kwargs.

What do you think? This method should be changed?

**Comment by pedrobaeza** [comment]
Hi, @hugosantosred, I think we can change it here in OCB, because in v8 this has been refactored to new API, and we find this problem in one spanish localization module (as you would know).

For me :+1: .

**Comment by StefanRijnhart** [comment]
Closing this after more than 1,5 years without activity
