### ISSUE TITLE
[7.0] (Some ?) yaml unittest not executed on travis

### ISSUE THREAD

**Issue by petrus-v** [OCA/OCB#467]
./addons module doen't appear to be test by travis: https://travis-ci.org/OCA/OCB/builds/120348200 
only ./openerp/addons looks to be tested

I figure out that because we are running those test on our CI and this one: delivery/test/delivery_tracking_ref_backorder.yml is failing!
- Impacted versions:
  Travis branch 7.0, 
  I haven't check other branches
- Steps to reproduce:

createdb delivery
bin/start_odoo -d delivery -i delivery --stop-after-init;
bin/start_odoo -d delivery --test-enable --test-file=addons/delivery/test/delivery_tracking_ref_backorder.yml
- Current behavior
  unit test test from delivery_tracking_ref_backorder.yml doesn't appear to be test on travis
- Expected behavior:
  unit test test from ./addons directory should be test by travis

---

Also to fix the test itself I wonder what should be the expected behavior!... If I understand, this unit-test make sure while doing a partial delivery the carrier tracking number should be kept by the first order done (the backorder) while it's remove on the initial shipment.

Assuming the unittest is relevant, I think we are completely loosing the track number!...

The unittest was add by this commit: 5aca7471b7ab2d0927dd38b22be01939730ef262
[MRG] fix partial delivery will copy tracking number in the backorder picking lp:1199858 port of https://code.launchpad.net/~camptocamp/openobject-addons/7.0-595239-opw-skh-afe/+merge/201002 to ocb https://launchpad.net/bugs/1199858

I think the behavior change with this one: f406847613fe352908ff52f1babc3083fe6042ef
[FIX] delivery: reset delivery info on duplicate/backorder  The tracking reference and other delivery references are not relevant to duplicated pickings. Overwrite copy to remove carrier_tracking_ref, volume and number_of_packages.  Add fallback on stock.picking.in and out to use copy method of stock.picking.  For partial delivery, the duplicated picking is the delivered order and the existing picking is the backorder of the delivery (why so much hate?). This means we have to switch the delivery info between the backorder and the delivered picking. Combo opw 615593 and 618802

**Comment by gurneyalex** [comment]
@petrus-v I don't thing the 7.0 branch was ever properly tested with Travis. @hbrunn did some changes to use OCA/maintainer-quality-tools but only in v8 and later. I don't know if there is a reason for not using this in v7. Maybe you could try and make a PR to update the 7.0 travis config and put it on par with the 8.0 branch?

**Comment by petrus-v** [comment]
@gurneyalex ok thanks for your reply, I'll try to find out what's wrong!

@hbrunn any advices?

**Comment by hbrunn** [comment]
I'd take 8.0's `.travis.yml` and naively try what happens when you change 8.0 to 7.0 where applicable

**Comment by pedrobaeza** [comment]
This has been already solved in PR #469
