### ISSUE TITLE
 Consultation supplier invoices

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/OCB#473]
**Impacted versions:**
8.0

**Steps to reproduce:**
When we entered the Provider tab to view your bills, we enter through the button "Supplier Invoice"

**Current behavior:**
does not show the corrective invoices

**Expected behavior:**
Show sales invoices and corrective invoices

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You have to report this to Odoo, not to OCB.
