### ISSUE TITLE
Should OCB have a specific README.md?

### ISSUE THREAD

**Issue by gdgellatly** [OCA/OCB#483]
Impacted versions: All

Steps to reproduce: Read the Readme

Current behavior: Installation steps are for the official odoo repo

Expected behavior: Installation steps are for the OCB repo

Video/Screenshot link (optional):

**Comment by elicoidal** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Well, last time this came up, the responses were mixed: https://github.com/OCA/OCB/issues/381

**Comment by pedrobaeza** [comment]
Checking history, for v11 it has been barely modified after the initial release (https://github.com/OCA/OCB/commits/11.0/README.md), so maybe we can give it a try again.

**Comment by SalahAdDin** [comment]
What's about a relasea or a `.deb` package? It would make more easy install it in production environments.

**Comment by blaggacao** [comment]
Hi, I'd like to give OCB a try and would actually be looking exactly for the contents of such readme.

**Comment by zeroheure** [comment]
IMO you just need to add a link to the Wiki, where you put instructions. So the Odoo Readme remains untouch except a short line at the bottom or the top.

**Comment by zeroheure** [comment]
See my work in the [Wiki](/OCA/OCB/wiki)

**Comment by zeroheure** [comment]
I suggest to close this.

**Comment by pedrobaeza** [comment]
Thanks for your work on the Wiki, Xavier. I have changed anyway the main README to point to this Wiki as reference on 14.0, 15.0 and 16.0.
