### ISSUE TITLE
Do I need an Odoo password to start using OCB?

### ISSUE THREAD

**Issue by ghost** [OCA/OCB#486]
Impacted versions: ALL

Dear all,

I installed OpenERP versions 6.04 and 7.0 for migration purpose on a GNU/Debian host. To my surprise, installing modules under OpenERP 7.0 requires an Odoo remote account (a free one as of April 2016). 

With recent news of Odoo becoming proprietary, I do not trust Odoo upgrade mechanism any longer.

I am downloading OCA from git. 
Will I need to register Oddo to install additional modules? 

I would like to rely only on github and free software. Is this the case with OCB? Could you confirm publicly that there is no link whatever with Odoo website installation mechanism.

Kind regards,
Kellogs

**Comment by pedrobaeza** [comment]
No, it doesn't require a password. It's only needed for downloading modules from Odoo's own store. Please don't open issues here where they should go (if adequate) in odoo/odoo.

**Comment by ghost** [comment]
Thank you for your answer : so OCB still relies on Odoo online services for third-party modules.
I am surprised ...

Frankly, I would prefer a mechanism where users have a possibility to rely on GIT to query modules, so we don't mix free software and proprietary software.

In other words, I would like to be able to query modules using GIT from OCB without relying on Odoo services for installing modules.

Some modules downloaded "freely" from Odoo are impossible or very difficult to upgrade. The only solution for "trapped" users are to register Odoo online services. This is not fair and this should not apply. The best is IMHO to cut the link with Odoo.

**Comment by pedrobaeza** [comment]
No, it doesn't need. It's your choice to use that menu option, and you also have the module disable_odoo_online (disable_openerp_online) to remove it.

**Comment by ghost** [comment]
Perfect, I was not ware that this module exist. But why not do the converse: install disable_odoo_online module by default and allow users to connect to Odoo if they request it?

99% of OCA users have no deep computing knowledge. When they install software from Odoo, they don't realise it is "mostly" non-upgradage, which can be a disaster in business.

I have been using OpenERP for more than five years now. I just upgraded from 6.03 to 7.0 and this is a "heck" (days of work). I am moving to 8.0. But I had to remove all non-standard modules. Only OCA modules work on the long run. Odoo is rub***, don't let users think it is easy to download, it is not true.

**Comment by pedrobaeza** [comment]
That decision corresponds to the user.

**Comment by ghost** [comment]
Frankly, in a free association, such a question needs some thinking, at least needs to be discussed in public.

If your name was Linux, you would probably not need to connect to a third-party service to download modules ... Or if you buy a car, you probably don't get parts from a third-party.

This kind of process mixing OCA with non-free software from Odoo is questionable.

**Comment by pedrobaeza** [comment]
OK, if you want to debate this, please use the proper channels: community mailing list.
