### ISSUE TITLE
[all] Please remove Odoo logo

### ISSUE THREAD

**Issue by ghost** [OCA/OCB#487]
Dear all,

Would it be possible to replace Odoo with OCB logo and moto wherever it appears, except Odoo online services, as explained here and commit to GIT:
http://odoo.guide/debranding-odoo-backend/

When using OCB, users may have the impression to use Odoo, when it is not true. OCB is fully free and Odoo is not.

Odoo 9.0 removed a lot of features from their community version.:
https://www.odoo.com/fr_FR/pricing

Letting users believe that they are using Odoo would not be fair. OCB is a different software, designed and build by a community, released free forever.

Kind regards,
Kellogs

**Comment by guewen** [comment]
Users using OCB _are using Odoo_, but a version with backports we judge useful to commit.
OCB does not position itself as a challenger to Odoo AFAIK.

**Comment by ghost** [comment]
The question is not the challenge by being fair to users to indicate clearly what is being used. Apparently, Odoo has so many editions, that it is not clear. Myself, being an OpenERP user for more than 5 years, it took me some time to understand. The average user cannot understand.

The name OCB with logo is clear and neutral.

**Comment by ghost** [comment]
Just consider binary packaging. If you are to release OCB in Debian or other distributions, you will have to ask permission to use the logo and name. If for some reason Odoo at some point disagrees, you will have to remove all binaries from repositories. It is simply not workable.

This is why in Debian firefox is being renamed "iceweasel". Can last for years and no need to ask permission to use a brand.

**Comment by pedrobaeza** [comment]
We don't plan to do such thing for now. It's not the scope of the project. The scope is only to provide additional fixings to the vanilla Odoo.

**Comment by dreispt** [comment]
@kellogs I agree with @guewen : OCB is Odoo + additional bugfixes, It is still Odoo, not a fork.
In the far case where using the Odoo brand becomes a problem, it would be easy to add a PR removing it.

**Comment by guewen** [comment]
> This is why in Debian firefox is being renamed "iceweasel". Can last for years and no need to ask permission to use a brand.

No longer true in debian unstable :) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815006

**Comment by ghost** [comment]
OK, you assume that OCB is not a fork. 

But how do you call the enterprise edition of Odoo 9.0 with complete accounting when Odoo 9.0 community has very poor accounting. OCA is not forking Odoo, OpenERP SA is forking Odoo. So both versions are forks. In the future, OpenERP SA will carry on more and more commercial and close source development.

And as a consequence, OCB is a fork of OpenERP/Odoo enterprise versions. You can't deny it. And you/we probably did not want it.

I am planning to provide debs and docker free images of OCB and Openupgrade. This will allow hosting of OCB on 3€/month services like https://www.scaleway.com. And as a consequence, there will be more contract jobs, more training sessions for small companies and individual developers and this will benefit the whole community, not OpenERP SA alone.

I don't want users to believe that cheap hosting using new technologies could be proposed by OpenERP SA and I don't want any conflict with the name Odoo. OpenERP chose to become a sole player and this is their choice, let them live with the money they raised and that they need to repay to investors.

This makes no sense to name Odoo OCB on Github and refuse to rename it in the console.

So let's rename Odoo to OCB. Hundreds of people will soon provide free hosting. Let's include ocb in Debian like it was the case of OpenERP before it was removed. I can take care and responsability for that, but we need to agree on a different name, not Odoo.

Odoo is dead, long live ocb.

**Comment by ghost** [comment]
What will you do in one year if the next version of Odoo are completely proprietary? 

If this is the case, all Odoo users will switch to OpenERP services and we will all become unemployed or OpenERP employees. This cannot happen and should not happen. The best way is to switch name quickly and massively release ocb as online free services and provide a consistent software able to upgrade quickly and smoothly, just like Drupal is able to do (with thousands of packages and millions of users).

We can't trust OpenERP SA to release the community version forever.

**Comment by gdgellatly** [comment]
Lol, my kids never understand why I say no either.

OCB is just a bug fix branch, not a separate product and no more or less
free than Odoo.

**Comment by dreispt** [comment]
@kellogs It shouldn't be hard to create an auto-installed module that does that debranding.
 IMO that could even be accepted in a repo llike oca/server-tools.

**Comment by gurneyalex** [comment]
such a change would be against the current OCB merge policy.

**Comment by ghost** [comment]
@gurneyalex: Could you point out the OCB merge policy?
@dreispt: A separate module is a good solution for a start.

@gdgellatly: So if I understand correctly, the goal of the association OCA is to provide free code to OpenERP SA when on the converse OpenERP SA is able to publish closed-source code and make money with free code. Nice eco-system, close to the definition of slavery (free work imposed to a community). 

IMHO, the only way to go is to accept the situation of "fork" imposed by OpenERP SA and make OCB as broad as possible: change name, publish packages, publish docker and hosting images.  And stay compatible, remain linked to Odoo repository for a while.

This way OCA can be strong. If we are not stong, Oddo 10 or 11 will be completely closed and this will be the end of the story. OpenERP SA is now governed by their obligation to reimburse millions of dollars, and if they have to close source, they will do it next time. They don't have a choice.

Remember that OpenERP SA can change licensing at any time now on.

You are **_very nice**_ with people of OpenERP when you answer "Wron't fix". Did you vote for that important decision?

**Comment by StefanRijnhart** [comment]
@kellogs As I am sure that you are aware, you are trying to extend the mission of OCB to be a fork of Odoo instead of a sheepish follower of Odoo with additional bugfixes that have not yet been processed by upstream Odoo. It is currently out of scope for this project. My advise to you is to try and gather momentum in the larger community to start up such a fork. If you can get the OCA to join in, we can easily create another Github project to host such a fork. I will be sure to participate in such a project. Closing this issue here though.
