### ISSUE TITLE
email_from ignored when send mail from template

### ISSUE THREAD

**Issue by dhecar** [OCA/OCB#508]
Impacted versions: 7

Steps to reproduce: create new mail template with explicit mail_from (ex: mymail@mydomain.com)

Current behavior:  The mail is sended but the From: is filled with user alias, not with the mail in template

Expected behavior: The From: is filled with the mail I fill in the template.

I have seen this old bug, but I don't know if it's solved because I get the same .

https://bugs.launchpad.net/openobject-addons/+bug/1193283

**Comment by StefanRijnhart** [comment]
Wrong project, I'm afraid. Try https://github.com/odoo/odoo
