### ISSUE TITLE
8.0 branch of OCB red on travis 

### ISSUE THREAD

**Issue by gurneyalex** [OCA/OCB#526]
Impacted versions: https://github.com/OCA/OCB/commit/01dea0b1d8a9a28525e9d111a73f2170bde796d4 and later

See https://travis-ci.org/OCA/OCB/builds/148741414#L7527

**Comment by pedrobaeza** [comment]
The pointed commit are only translations. There should be another cause...

**Comment by StefanRijnhart** [comment]
After a rebuild, the same commit is green again. It must have been the illuminati.

**Comment by gurneyalex** [comment]
I think this is a TZ related bug somewhere in the timesheet code or more likely in the timesheet tests (seeing that the build was red on the first day of the month, shortly after midnight UTC+2), causing a timestamp to be on the previous day. 

I don't have the guts to dig into this, though.
