### ISSUE TITLE
[REF] travis test - False positive not install all modules

### ISSUE THREAD

**Issue by moylop260** [OCA/OCB#53]
There are many false positive PR with travis.
I see log of build travis and just is installed base module.
[travis build pull/18](https://travis-ci.org/OCA/OCB/builds/35311558)
[travis build pull/49](https://travis-ci.org/OCA/OCB/builds/35439478)

This make a positive but when you install all modules is negative.

Check my last comment here:
https://github.com/OCA/OCB/pull/18#issuecomment-56317733
https://github.com/OCA/OCB/pull/49#issuecomment-56018414

**Comment by pedrobaeza** [comment]
Is this still happening?
