### ISSUE TITLE
Taxes Dropdown Problem in Purchase Order Line, Sale Order Line, Customer Invoices and Vendor Bills

### ISSUE THREAD

**Issue by ovnicraft** [OCA/OCB#534]
Impacted versions:

9.0

Steps to reproduce:

Open an invoice line, set taxes, try to remove one.

Current behavior:

Dropdown dont show list or show list moved.

Expected behavior:

Dropdown as list

Video/Screenshot link (optional):

I link the bug reported on odoo repo https://github.com/odoo/odoo/issues/10955

**Comment by firelz** [comment]
I have ran into the same issue..there is a solution trying placing 'delete icon' before text for FieldMany2ManyTag, addon/web/static/src/xml/base.xml
`<t t-name="FieldMany2ManyTag">
    <t t-foreach="elements" t-as="el">
        <span t-attf-class="badge dropdown #{'o_tag_color_' + (el['color'] || 0)}" t-att-data-color="(el['color'] || 0)" t-att-data-index="el_index" t-att-data-id="el['id']">
            <span t-if="!readonly" class="fa fa-times o_delete"/>
            <t t-esc="el['display_name']"/>
        </span>
    </t>
</t>`

**Comment by pedrobaeza** [comment]
Thanks for the reporting, but this is only valid in Odoo. OCB is for proposing patches, not issues. Only issues related to the OCB patches (not Odoo in general) are hosted here.
