### ISSUE TITLE
[10.0] Allow Cancelling Entries not found in Journal Advanced Settings

### ISSUE THREAD

**Issue by SamirSaidani** [OCA/OCB#582]
Impacted versions:
10.0
Steps to reproduce:
- as administrator, in Settings, activate the developer mode
- go to Accounting>Configuration>Accounting>Journals
- go to Customer Invoices Journal>Advanced Settings

Current behavior:
in Miscellaneous, we see
- Group Invoice Lines 	
- Show journal on dashboard 

Expected behavior:
in Miscellaneous, we should see
- Group Invoice Lines 	
- Allow Cancelling Entries 	
- Show journal on dashboard

**Comment by pedrobaeza** [comment]
You mustn't publish issues in this fork, but on the main one. Anyway, your problem is that you haven't installed _account_cancel_ module itself.

**Comment by SamirSaidani** [comment]
Sorry, I'm starting to contribute, and not used to the current best practice. Isn't the main one the same than the default branch, aka 10.0 ?

As far as I understand, account_cancel does not need to be installed, it is already present in the 10.0 branch : see https://github.com/OCA/OCB/tree/10.0/addons/account_cancel.

Moreover, when I go to https://www.odoo.com/apps/modules/10.0/account_cancel/, to download the module, the page ask me to download Odoo CE, which is consistent with this interpretation.

Same kind of problem with 9.0 was identified here, though not sure it's related :
https://github.com/odoo/odoo/issues/8532

**Comment by pedrobaeza** [comment]
I mean https://github.com/odoo/odoo

**Comment by SamirSaidani** [comment]
Ok thanks ! are you sure that we need to install the account_cancel module ? It looks like it's included by default now for the 10.0 branch (and 9.0).

**Comment by SamirSaidani** [comment]
ok we can close this issue, I've discovered a while ago that you need to delete all the tags on the application research text zone, and then the account_cancel would appear. Looks like a newbie mistake (or a UX not so intuitive design...).
