### ISSUE TITLE
[10.0] wrong calculation of worked days on payslip

### ISSUE THREAD

**Issue by raditv** [OCA/OCB#595]
Impacted versions:
10.0 on [Runbot](http://3282256-10-0-c5c01b.runbot1.odoo-community.org)
Steps to reproduce:
Creating working hours with start and end date for each day (shift working hour)
![1](https://cloud.githubusercontent.com/assets/1745955/23779596/efaefece-0573-11e7-92a3-9b901750479e.png)
Current behavior:
![2](https://cloud.githubusercontent.com/assets/1745955/23779852/8db75db8-0575-11e7-9376-4cbe7f54b030.png)
Expected behavior:
![3](https://cloud.githubusercontent.com/assets/1745955/23779864/a0b6302e-0575-11e7-85cd-0515045f8c54.png)

Video/Screenshot link (optional):

**Comment by raditv** [comment]
@nim-odoo you may take a look at this

**Comment by pedrobaeza** [comment]
You have put the issue on OCA/OCB, not on odoo/odoo.
