### ISSUE TITLE
V10  Manufactured item cost is not calculated from Component cost no matter costing method is set to real price or avaerage

### ISSUE THREAD

**Issue by bunhin** [OCA/OCB#618]
Impacted versions: V10
For manufactured item with costing = real price, stock valuation = perpetual, removal not set or set to fifo, with or without tracking, the manufactured item is not taking cost from the component cost on the BOM or from added consumed component. Instead it is only take the cost from field cost in product form no matter the cost is not set ( 0 ) or set to a value.

Expected behavior : The cost need to be taken from respected component cost used.
in V9 this behavior is ok although only work when costing method = real price, when changed to average not work anymore.

Steps to reproduce:

Set category product with: all/saleable as parent category.
Set costing method = real cost
set stock valuation method = perpetual
set or not set the "force removal method" to fifo or keep empty
set respected account for stock move in this category

Create product A route = buy fill in product price dan cost with a value
Create product B route = buy fill in product price and cost with a value
Create product C route = buy, manufacture is checked fill in product price with a value, keep cost field = 0
Create a BOM for product C with A and B as component set usage = 1 each for A and B
Purchase product A and B for some quanity eg 5 each and confirm, then receive and validate the receipt
Create MO for Product C set qty eg = 2 and used the created BOM as above.
confirm the MO and start the work order, finish it, mark as Done the MO

Go to inventory valuation
we will find the qty of manufactured product C is added for 2 pcs (as MO qty) but the cost is 0
while product A and B qty already reduced by 2 pcs each with respected purchase cost. (same with filled cost in product form if it is not changed during PO creation)

Current behavior:
Cost of manufactured product C is not calculated from component cost

Expected behavior:
Cost of manufactured product C is calculated from component cost consumed. at least same as V9

Have written this also in odoo/odoo git
Is it by design to reduce community feature?

**Comment by pedrobaeza** [comment]
This should be published on odoo/odoo, not here.
