### ISSUE TITLE
Fix produces XML Xpath errors in 'purchase' product_views 

### ISSUE THREAD

**Issue by awa-si** [OCA/OCB#622]
Impacted versions: 10

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

with this fix
https://github.com/OCA/OCB/commit/92be0df468c3f467e078be18a13ab1cf5215f376?diff=unified
threw XML errors in purchase module XML file product_views
If commented out lines 397 - 410, everything is fine

**Comment by pedrobaeza** [comment]
Is this something specific to OCB or it happens in Odoo as well? If so, please put the issue in odoo/odoo, not here.

**Comment by awa-si** [comment]
@pedrobaeza it's a specific to odoo generally at odoo/odoo
