### ISSUE TITLE
[7.0] Decimal Precision

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/OCB#629]
Impacted versions:
---------------------
 7.0 No (yet) checked for other versions

Steps to reproduce: 
---------------------
run travis test

Current trouble:
-------------------
```
File "/home/travis/OCB-7.0/addons/account/account.py", line 36, in <module>
    import openerp.addons.decimal_precision as dp
AttributeError: 'module' object has no attribute 'decimal_precision'
```

Reason
--------

File ./addons/account/account.py (and some other files too) use follow declaration:
`import openerp.addons.decimal_precision `

but module decimal-precision is not under ./openerp./addons but is unade ./addons
The right declaration should be simply:
`import decimal_precision `

Proposed solution (apply for local repository):
--------------------------------------------------

1. Search for all affected files:
`find ~/7.0 -name "*.py" -exec grep -l "import openerp.addons.decimal_precision" '{}' \;`
2. Replace
`find ~/7.0 -name "*.py" -exec sed -i -e "s/import openerp.addons.decimal_precision/import decimal_precision/g" '{}' \;`

**Comment by gdgellatly** [comment]
I'm pretty sure those import statements are correct.

I'm not technical enough to explain it exactly but there is a namespace? openerp.addons created when you start the server that contains all of the addons, regardless of directory structure based on the config file addons_path.

So for example lets say you wanted to overwrite the method write of your_module_xxx in any directory anywhere in the addons_paths (bad example here, definitely don't do this in practice, I just couldn't think of a better example)

```python
import openerp.addons.yourmodule_xxx

def write(*args, **kwargs)
    return True

openerp.addons.yourmodule_xxx.your_class.write = write
```
No need to know the underlying directory structure.  At least I'm pretty sure thats how it works.

**Comment by zeroincombenze** [comment]
Look at this log travis
https://travis-ci.org/zeroincombenze/bank-payment/jobs/255002792

The error is in OCA module

**Comment by pedrobaeza** [comment]
This was fixed long time ago.
