### ISSUE TITLE
[8.0] Group tax based on Tax code

### ISSUE THREAD

**Issue by kenvac** [OCA/OCB#630]
Impacted versions:
8.0
Steps to reproduce:
* Install module l10n_uk
* Choose UK Charts of account while installing accounting chart
* Create new Customer invoice
* Choose ST11 and ST1 tax on invoice line (both tax has same account tax code and tax account)
* Compute tax on invoice
* Go to Other info tab
* Check Tax entries

Current behavior:
* Odoo currently[8.0] group by tax entries on base account code and tax account.
* There could be tax with same tax account and tax code but would still like to show them separately and invoice. 

Expected behavior:
* The tax group by should be done on tax code e.g ST11, ST1 and so on
* There should two tax line one for ST11 and second for ST1 

REF : https://bugs.launchpad.net/openobject-addons/+bug/1108801

odoo 9 and onwards does it correctly.

Let me know if more information is require

**Comment by pedrobaeza** [comment]
Closing the same as the PR. See comments there.
