### ISSUE TITLE
[8.0] Confirming a quotation raises 'Document missing' exception

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/OCB#646]
**Impacted versions:** 8.0

**Steps to reproduce:**
- Create a quotation with some mistake in it, that would raise an exception when confirming, [for example this one](https://github.com/OCA/OCB/blob/8.0/addons/mrp/mrp.py#L344)
- Try to confirm the quotation
- Watch the MissingError (document not there or missing) exception being raised on [this line](https://github.com/OCA/OCB/blob/8.0/addons/procurement/procurement.py#L217).

Current behavior:
- Show user the unhelpful MissingError

Expected behavior:
- Show user the real error that needs to be dealt with

**Comment by thomaspaulb** [comment]
@mistotebe @beledouxdenis have found a bug with [your code](https://github.com/OCA/OCB/blame/8.0/addons/procurement/procurement.py#L217) and hopefully fixed it for good, please review so that it can be merged.

**Comment by pedrobaeza** [comment]
This should be in odoo/odoo, not here.
