### ISSUE TITLE
[9.0] pos confirm paiement Raises 'Nothing to check the availability for'

### ISSUE THREAD

**Issue by meriemH** [OCA/OCB#651]
Impacted versions: 9.0

Steps to reproduce:

- Create an order with return of goods and sell of service
Feg : -1 product
         +1 service

- Then confirm the paiement.

Current behavior:

Warning Message :  Nothing to check the availability for

Expected behavior:

Correct confirmation of the paiement.

Proposition-Code information:

file : addons/point_of_sale/point_of_sale.py
function :  def create_picking(self, cr, uid, ids, context=None):
        """Create a picking for each order and validate it."""
raised error : (at stock movement level)
            if not move_ids:
                raise UserError(_('Nothing to check the availability for.'))

suggested correction :  
create 
order_picking (resp return_picking) only if exists positiv (resp negative) order.line that are **not** services.
 
                pos_qty = any([ ( x.qty > 0 and x..product_id.type in ['product', 'consu']) for x in order.lines])
                if pos_qty:
                    order_picking_id = picking_obj.create(cr, uid, picking_vals.copy(), context=context)
                neg_qty = any([ ( x.qty < 0 and x..product_id.type in ['product', 'consu']) for x in order.lines])
                if neg_qty:
                    return_vals = picking_vals.copy()
                    return_vals.update({
                        'location_id': destination_id,
                        'location_dest_id': location_id,
                        'picking_type_id': return_pick_type.id
                    })
                    return_picking_id = picking_obj.create(cr, uid, return_vals, context=context)

**Comment by pedrobaeza** [comment]
This should be in odoo/odoo, not here.
