### ISSUE TITLE
[8.0] Calendar event read access error

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [OCA/OCB#652]
Hi,

Odoo has global record rule with the following domain:
`
['|',('user_id','=',user.id),('show_as','=','busy')]
`
Which triggers an error when trying to show the user a calendar event notification of which is an attendee and not the owner.

Also i would like to ask you why the notification triggers each 5 min and can't be changed:
```python
def get_next_notif(self, cr, uid, context=None):
    ajax_check_every_seconds = 300
    ...
```

Impacted versions:
OpenERP version 8.0
Addon calendar version 1.0

Steps to reproduce:

1. Create a calendar event with an attendee different from the owner
2. Set the meeting to be recurrent
3. Login with the attendee user

Current behavior:
![access_error](https://user-images.githubusercontent.com/23120306/30861797-25dd442e-a2cc-11e7-88b0-bcc225b6ca22.png)

Expected behavior:
Show the event notification to the attendee.

Best regards,
Luis

**Comment by pedrobaeza** [comment]
I don't think this is something specific of OCB, but common to Odoo, so you have to notify to odoo/odoo, but bad news, Odoo is not supporting anymore 8.0, so...

**Comment by ljsalvatierra-binovo** [comment]
My mistake, thank you for you quick response.

**Comment by schiffsratte** [comment]
Even if it's old and closed, it's still prominent on google-search:
This Error happens, if you create Events (with notifications) with the admin user and you invite normal users.
Whenever the normal user is supposed to be notified by the popup, it throws this error as a user has no right to see admin's events even when the user has been invited to it
