### ISSUE TITLE
Will you migrate dropped modules, like marketing_campaign and project_issue?

### ISSUE THREAD

**Issue by backendoadmin** [OCA/OCB#656]
I saw Odoo dropped those module and built new enterprise only version for those funkctions. I think theese 2 are essential for an ERP. Are you plannaing to upgrade these modules?

Thank you

**Comment by pedrobaeza** [comment]
At least not here. OCB is not for this. Personally the merge of tasks and issues for me is a good move.

**Comment by backendoadmin** [comment]
Where should I ask? I just come here from odoo forum: 
https://www.odoo.com/forum/help-1/question/how-to-use-projects-to-handle-issues-on-odoo11-124735

**Comment by pedrobaeza** [comment]
I rephrase: OCB won't host new modules. It's a branch for hosting only patches in Odoo core. If someone wants to forward port that modules, and bring them to OCA, they will propose them to OCA/project or similar. But I don't know the plans of everyone. As said, I personally won't fill the project_issue module and use the tasks for that purpose, now that they include the same fields as issues.
