### ISSUE TITLE
Travis is disabled for OCB

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OCB#660]
Travis is not run on new PRs since yesterday.

https://travis-ci.org/OCA/OCB: 

"This is not an active repository.
You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself."

@pedrobaeza @moylop260

**Comment by pedrobaeza** [comment]
Uhm, curious. I have enabled it just now.
