### ISSUE TITLE
[8.0] Project timesheet button: invisible condition not working

### ISSUE THREAD

**Issue by jonerikceberio** [OCA/OCB#671]
Minimal issue, but takes more time to read it than solve it.

Impacted versions: 8.0

Steps to reproduce: Create a project, uncheck the "Use timesheets" checkbox, the button to timesheets does not dissapear

Current behavior: does not dissapear

Expected behavior: The button should go invisible

Solution:
https://github.com/OCA/OCB/blob/70e35cb40c578e0a4c0879495e932da6fd2a9829/addons/project_timesheet/project_timesheet_view.xml#L33
Replace the invisible condition for:
attrs="{'invisible':[('use_timesheets','=', False)]}"

-----------------------------------
Other versions:

- 9.0: the button does not even have an invisible condition: https://github.com/OCA/OCB/blob/7f70d151a659c1e2979283cb5225a7b9351e5736/addons/project_timesheet/project_timesheet_view.xml#L11

- 10.0: Works perfectly: https://github.com/OCA/OCB/blob/151a7c97b0c330959d9dd2c3a05b5e96fe926e0e/addons/hr_timesheet/project_timesheet_view.xml#L46

**Comment by pedrobaeza** [comment]
If this is an Odoo bug, not OCB specific, it shouldn't go here, but on odoo/odoo. Any way, Odoo does no longer maintain 8.0 version, so if you propose a PR to this OCB version, it can be accepted.
