### ISSUE TITLE
[10.0] Test build fails on OCB but passes on Odoo

### ISSUE THREAD

**Issue by dreispt** [OCA/OCB#682]
PR: https://github.com/OCA/project/pull/329
Log: https://travis-ci.org/OCA/project/jobs/289429902#L1292

It is related to `project_issue` and the `portal` modules.
Any ideas why?

**Comment by hbrunn** [comment]
some of the portal modules used to be autoinstall in upstream, what we disabled in ocb. Unfortunately, upstream's tests sometimes rely on autoinstalled modules without dependency. So to make this work in ocb, depend explicitly on what your dependencies' tests or your own tests need. First try to convince upstream to add a proper dependency, sometimes this works.

**Comment by dreispt** [comment]
Thank you Holger.
In this case it is not tests related: the `project_issue` module fails to install with demo data.

I don't want red builds. 
What do you suggest as a workaround?

**Comment by hbrunn** [comment]
submit a patch to OCB to not use xmlids in demo data that the module doesn't depend on. I think you'll make the world worse if you just add a dependency, so I'd rather recreate whatever data is used there.

I'm totally sure we had this exact discussion a while ago about 9 or 8, but can't find it at the moment. Also not so sure if it was the same modules, but we had this before.

**Comment by dreispt** [comment]
OK, I'll propose an OCB patch.

**Comment by pedrobaeza** [comment]
Solution in #691
