### ISSUE TITLE
Is portal a project_issue depend???

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/OCB#683]
https://github.com/OCA/OCB/blob/0e6f1ee84b488d874d51bdf3be5a8bfb90ee19aa/addons/project_issue/data/project_issue_demo.xml#L39

**Comment by pedrobaeza** [comment]
Indeed. We deactivated auto_install=True in portal, but the dependency chain is not correct here and relies on the auto_install property. We should add the dependency, but in Odoo itself.

**Comment by DarioLodeiros** [comment]
#684

**Comment by astirpe** [comment]
#691
