### ISSUE TITLE
[10.0] web addon give 404 on static files (icons, images, css)

### ISSUE THREAD

**Issue by scigghia** [OCA/OCB#693]
Impacted versions:
10.0 OCB
Steps to reproduce:
start odoo also after clean install
Current behavior:
show symbols instead icons and images
Expected behavior:
expect correct icons and images

i've manually copied wed folder from here https://github.com/odoo/odoo/tree/10.0/addons/web and my odoo works correctly, so i think problem is web folder from ocb

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Have you tried on OCB runbot?

**Comment by scigghia** [comment]
is not a ocb o odoo problem, but if there are broken addons , the error causes web addon stop working

**Comment by pedrobaeza** [comment]
This should be put on odoo/odoo, not here.
