### ISSUE TITLE
[10.0] Failed travis build

### ISSUE THREAD

**Issue by p-tombez** [OCA/OCB#708]
Impacted versions: 10.0

Steps to reproduce: N/A

Current behavior: Travis build fail with errors in the website tests (see build link for complete error)

Expected behavior: Travis build succeed

Video/Screenshot link (optional):
https://travis-ci.org/OCA/OCB/builds/349566960

**Comment by randall-vx** [comment]
@pedrobaeza Hi Pedro, can anyone help with this error ? Regards.

**Comment by pedrobaeza** [comment]
Rebase and try again because the error that appears seems linked to something that Odoo screwed up.

**Comment by pedrobaeza** [comment]
Travis build is fixed.
