### ISSUE TITLE
[9.0] Failed travis build

### ISSUE THREAD

**Issue by p-tombez** [OCA/OCB#709]
Impacted versions: 9.0

Steps to reproduce: N/A

Current behavior:
Travis build fail on start
```
$ pip install -r ${HOME}/maintainer-quality-tools/travis/requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: '/home/travis/maintainer-quality-tools/travis/requirements.txt'
```

Expected behavior: Travis build succeed

Video/Screenshot link (optional):
https://travis-ci.org/OCA/OCB/builds/349567017

**Comment by pedrobaeza** [comment]
It seems a glitch, please try again.
