### ISSUE TITLE
[9.0]vendor pricelists is not used for invoice

### ISSUE THREAD

**Issue by dlemireanybox** [OCA/OCB#713]
Impacted versions: V9

Context: 
 purchase only installed
 
Steps to reproduce: 
    0) use purchase settings:  "Allow using and importing vendor pricelists"
    1) for a product with cost 5$, create a price  for  supplier "A" equal 100$
    2) create invoice from this supplier
    3) add quantity of 1 product

Current behavior:
   the line price is equal 5$
Expected behavior:
   the line price must be equal 100$
Video/Screenshot link (optional):
Impacted versions: V9

Context: 
 purchase only installed
 
Steps to reproduce: 
    0) use purchase settings:  "Allow using and importing vendor pricelists"
    1) for a product with cost 5$, create a price  for  supplier "A" equal 100$
    2) create invoice from this supplier
    3) add quantity of 1 product

Current behavior:
   the line price is equal 5$
Expected behavior:
   the line price must be equal 100$
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You should create these issues in odoo/odoo, not here.
