### ISSUE TITLE
[9.0] bug product:  taxes vendor  not display all the availables taxes 

### ISSUE THREAD

**Issue by dlemireanybox** [OCA/OCB#714]
Impacted versions:
 [9.0]
Context: 
    purchase only installed
    
Steps to reproduce:
    1) from product "A" create a vendor taxe "B"
    2) save the product with taxe "B"
         
Current behavior:
    after save,  in the product "A"  the vendor taxe value is erased and is blank
    the new taxe "B" is not appeared in the list of availables taxes
    the same problem occurs in  setting of invoicing for the vendor taxe
Expected behavior:
     the vendor taxe must have the customer taxe behavior
     when create from a product or  setting of invoicing=> not erased and appear in list
     
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You should create these issues in odoo/odoo, not here.
