### ISSUE TITLE
[10.0] Partner's roule raises res.users read error

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/OCB#724]
Impacted versions: **10.0**

Steps to reproduce:

Create a new user's group with this roule:

**Object**: _Partner_
**Rule Definition**: _['|',('user_id','=',user.id),('user_id','=',False)]_

Current behavior:

When a user of this group try to create a sale order, Odoo raise this error:

**(Document type: res.users, Operation: read)** 

Odoo logs:

```
odoo.api: call sale.order().create({u'origin': False, u'message_follower_ids': False, u'weight': 0, u'order_line': [], u'picking_policy': u'direct', u'ddt_carrier_id': False, u'create_ddt': False, u'team_id': 1, u'client_order_ref': False, u'date_order': u'2018-03-28 20:03:44', u'partner_id': 25, u'message_ids': False, u'user_id': 11, u'company_id': 1, u'note': False, u'pricelist_id': 1, u'project_id': False, u'incoterm': False, u'transportation_method_id': False, u'ddt_invoicing_group': u'billing_partner', u'validity_date': False, u'warehouse_id': 1, u'volume': 0, u'payment_term_id': False, u'partner_invoice_id': 25, u'fiscal_position_id': False, u'transportation_reason_id': False, u'partner_shipping_id': 25, u'carriage_condition_id': False, u'parcels': 0, u'goods_description_id': False})

werkzeug: xxx.xxx.xxx.xxx - - [xx/xx/2018 20:03:54] "POST /web/dataset/call_kw/sale.order/create HTTP/1.1" 200 -
```

**Comment by pedrobaeza** [comment]
This project is only for issues on OCB specific fork. Any way, this is not a bug, but a question.

**Comment by protontrigg3r** [comment]
I'm really sorry if I made a mistake.

I'm using a clean Odoo OCB installation and it was very strange for me to introduce a rule for "Partner" and obtain a restriction for "User".

This is why I was thinking to a bug.
