### ISSUE TITLE
Product form view bom button not display MO from Product Variant

### ISSUE THREAD

**Issue by pauloneda** [OCA/OCB#729]
Impacted versions:
8.0
Steps to reproduce:
Click Button Manufacturing on product.product Form
Click Button Manufacturing on product.template Form
Current behavior:
On click product.template form display all MO,
On click button in product.product form not display MO

Expected behavior:
On click button in product.product form display MO from Product Variant
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this issue tracker is only for specific problems with OCB, not with Odoo, but Odoo has already expired the 8.0 version because it's too old, so you are on your own...
