### ISSUE TITLE
I couldn't receive same lot product twice Selected Tracking by lots not unique serial numbers

### ISSUE THREAD

**Issue by carlosecv** [OCA/OCB#741]
Impacted versions: 11.0 CE

Steps to reproduce:
You must have tracking lots on products 

Current behavior:
Create  a product with tracking by lots
Receive one Lot number on inventory, then try to receive 
I couldn't receive same lot product twice Selected Tracking by lots not unique serial numbers

Expected behavior:

the product is setting Tracking: By Lots. so if we use a lot number that has been used earlier the sistem must use it and not to try to create it we receive:

The combination of serial number and product must be unique!

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You have to put the issue in odoo/odoo, as this is not an specific issue of OCB.
