### ISSUE TITLE
[11.0] purchase: purchase order line decrease quantity

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [OCA/OCB#797]
https://github.com/OCA/OCB/blob/cbaf57f193626798de8592ce91263db0c395477c/addons/purchase/models/purchase.py#L733

Hi, i'm curious about why it is only possible to increase the quantity to receive and not decrease, because it is not possible to decrease below received quantity. Nonetheless, you could possibly want to decrease the quantity before you have receive any goods.

https://github.com/OCA/OCB/blob/cbaf57f193626798de8592ce91263db0c395477c/addons/purchase/models/purchase.py#L654

Thanks.

**Comment by pedrobaeza** [comment]
This issue tracker is only for OCB specific issues, not general Odoo ones.

Any way, you should make your question in forums/lists, as this is also not an issue, but a question.

**Comment by ljsalvatierra-binovo** [comment]
My bad, sorry to bother. I've [published my question](https://www.odoo.com/es_ES/forum/ayuda-1/question/11-0-purchase-update-picking-stock-move-when-purchase-order-line-decrease-in-quantity-139929) in the Odoo forum if anyone is interested.
