### ISSUE TITLE
[8.0][warning] Installing warning module results in empty request.env.user object

### ISSUE THREAD

**Issue by robch2342** [OCA/OCB#806]
Impacted versions: 8.0

Steps to reproduce:
Install warning and website.
Print active user on a page (`<t t-esc="request.env.user"/>`).
Restart odoo and load the page.

Current behavior: The request.env.user object will be empty the first 1 - 3 (possibly more) page loads.

Expected behavior: The request.env.user object should always be set.

**Comment by pedrobaeza** [comment]
Please don't open issues if you are going to put a PR. Put the issue description directly in the PR.
