### ISSUE TITLE
Error lines duplicated

### ISSUE THREAD

**Issue by jado95** [OCA/OCB#817]
Impacted versions:
8.0
Steps to reproduce:
I have a draf invoice, edit the invoice and add a line with product and tax 22V (or other tax), and validate the invoice and i have the error : 
`Tax base different!
Click on compute to update the tax base`
In this point if i save the invoice, i have the invoice line duplicated.

Similar error in sale order or on account.move. Sometimes when edit order, add lines and validate order, on the order there are duplicated lines.

**Comment by pedrobaeza** [comment]
Sorry, this issue tracker is only for specific bugs in OCB distribution, not in Odoo in general, and version 8 is already deprecated by Odoo, so you are at a dead end. Any way, this is how Odoo behaves in this version.
