### ISSUE TITLE
why in the install doc (https://github.com/OCA/OCB/blob/11.0/doc/setup/install.rst) about wkhtmltopdf for ubuntu/debian The recommended version is 0.12.1 and fedora The recommended version is 0.12.5 ? not also the ubuntu one ?

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/OCB#820]
Impacted versions: 11

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
@andreampiovesana This is an upstream issue. Best to try on the odoo project. This branch just contains backports of critical nonbreaking bug fixes

**Comment by pedrobaeza** [comment]
That's it, closing then.
