### ISSUE TITLE
ValueError: Le champ `team_id` n'existe pas

### ISSUE THREAD

**Issue by EBII** [OCA/OCB#821]
Impacted versions:12.0

Steps to reproduce:install sale and create invoice

Current behavior: need to have crm install

Expected behavior: still working without crm

Video/Screenshot link (optional):
can not go into invoice menu
Warning with stack trace ValueError: Le champ `team_id` n'existe pas

it was working last week then i decide to update OCA/OCB with git pull this mornig of 02/01/2019 
so i install crm to solve the trouble..

**Comment by pedrobaeza** [comment]
Sorry, but this issue tracker is for notifying specific OCB issues, and this seems more a deployment/custom DB problem.
