### ISSUE TITLE
[11.0] BUG IN MULTICOMPANY

### ISSUE THREAD

**Issue by cesarsc79** [OCA/OCB#827]
Impacted versions:
[11.0]
Steps to reproduce:
one user in multicompany and acces rights for company A and company B

from a company A go to any model and add a report to My dashboard
Go to Board and i can see it with .... all OK

If you select other company (company B) and go to my dasboard

ERROR

If you select the company A again and go to my dashboard   ALL OK

If you add any report to dashboard from Company B and go to my dashboard     ERROR

It look like that all report are associated to same dashboard, 
the company a reports, and company b report ARE in the same BOARD (my board)

current behavior:

SO when you want go to my dashboard which have many report of differents companys in an enviroment multicompany

ERROR

Expected behavior:

Dashboard associated with company, for fix the bug

Video/Screenshot link (optional):

![captura](https://user-images.githubusercontent.com/25187665/51219411-28327c80-1931-11e9-91c6-a9c9c1d206aa.JPG)

**Comment by pedrobaeza** [comment]
This issue tracker is for issues related to OCB only, but this is Odoo.

Any way, the problem you have is that you can't put boards referring to several companies, or you will have problems when you are in other company. It's a limitation, but an understandable one.
