### ISSUE TITLE
[11.0] Resource calendar work days iterator

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [OCA/OCB#843]
Hi, first i would like to clarify why i publish the issue here and not in the repository ``odoo/odoo``, because i am not sure where it belongs.

Impacted versions:
11.0 
https://github.com/OCA/OCB/blob/e7b41b7fc316d802aec4d3acae30b8f6480487a1/addons/resource/models/resource.py#L414

Steps to reproduce:
Give a ``date from`` and ``date to`` to the method ``_iter_work_days`` to obtain a working dates iterator.

Current behavior:
The ``date to`` is not included, even if it is a working date.
In the method ``_iter_work_intervals`` the ``end time`` is calculated as follows:
```python
if day.date() == end_dt.date() and end_dt.time() != datetime.time():
    end_time = end_dt.time()
```
There are a couple of things i do not understand, first, why the ``end_time`` of the last day is not ``23:59:59`` as the rest of the days, and second, why there is a comparison between the current time and ``end_dt`` time.

Expected behavior:
The ``date to`` should be included in the iterator if it is a working date.
As shown in the screenshot, the ``end_time`` of the ``end_dt`` is ``1:00``, i understand it should be the same as the other days.

Screenshots:
![image](https://user-images.githubusercontent.com/23120306/55004666-ebdb6680-4fda-11e9-96b6-b9786a39c6da.png)

Kind regards,
Luis J. Salvatierra

**Comment by pedrobaeza** [comment]
On which saas branch is this?

**Comment by ljsalvatierra-binovo** [comment]
> On which saas branch is this?

2017-07-14: aa19cb61f4596b340ca05199d9e4d55ef9e34edb -> saas-14
2017-10-20: 10128fa7e8c743e9c838743204fb8116bcdeefd6 -> saas-16
2018-02-22: e5987434c6be7bab9102dc6aa2b4c6f03ee9dcc0 -> saas-15

But the issue is still present with the last commits.

**Comment by pedrobaeza** [comment]
But that ones are the commits that moves changes to 12.0. Any way, if in 11.0 there's no such commit, then it's legit to backport that feature here in OCB.

**Comment by ljsalvatierra-binovo** [comment]
> But that ones are the commits that moves changes to 12.0. Any way, if in 11.0 there's no such commit, then it's legit to backport that feature here in OCB.

Yeah, you are right, i am a bit confused on how Github shows the history changes... Anyway, I've edited the issue to show only the problem i've detected. Thank you.

**Comment by pedrobaeza** [comment]
But the problem is in vanilla Odoo v11? If so, then the issue doesn't belong here. If you want to backport a commit in v12 for solving sooner a problem that is not present in v12, but yes on v11, then put here the PR, but the requirement is that you give the same opportunity in Odoo making the pull request there.

**Comment by ljsalvatierra-binovo** [comment]
> But the problem is in vanilla Odoo v11? If so, then the issue doesn't belong here. If you want to backport a commit in v12 for solving sooner a problem that is not present in v12, but yes on v11, then put here the PR, but the requirement is that you give the same opportunity in Odoo making the pull request there.

Yes, ok, we will make the PR in vanilla Odoo v11. Thank you for your time.

**Comment by pedrobaeza** [comment]
But as said, you can propose the same change here and promote for being merged although Odoo doesn't do it yet.
