### ISSUE TITLE
how to create refund from stock_picking for customer returned products in odoo 11

### ISSUE THREAD

**Issue by Rathnakreeswaran** [OCA/OCB#845]
Impacted versions:
how to create refund from stock_picking for customer returned products in odoo 11

Current behavior:
i am unable to create refund and invoice from stock.picking!!!!!!!

Expected behavior:
I want to create invoice for outgoing shipments(Delivery Order) and also create refund for incoming shipments(Receptions) in odoo 11 from stock picking.

**Comment by pedrobaeza** [comment]
Sorry, this is not an OCB specific issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
