### ISSUE TITLE
[11.0] Country code not checked in base_vat

### ISSUE THREAD

**Issue by elarapuntsistemes** [OCA/OCB#848]
Impacted versions: 11 and above

**Steps to reproduce:**
1. Install base_vat module.
2. Create a new partner and select a country. I.e.: Belgium
3. Write a vat number without country code. I.e.: 0477472701
4. Save.

**Current behavior:**
As you can see in the image, Odoo allows to save the partner without the country code.

![imagen](https://user-images.githubusercontent.com/17743542/57134221-b843e700-6da5-11e9-8e8a-e2272c07a78a.png)

**Expected behavior:**
This feature was working different in previous versions: 10.
It was mandatory to write country code in the vat number field, otherwise, it didn't allow to save.

![imagen](https://user-images.githubusercontent.com/17743542/57134355-3bfdd380-6da6-11e9-9af4-c1778a818f49.png)

**Comment by pedrobaeza** [comment]
That's on purpose. Now Odoo allows to not putting the code. For VAT number check, put the country in the partner.

P.S.: This is not the place for putting the issue, but odoo/odoo.
