### ISSUE TITLE
[11.0] extension is added even if the file has already one

### ISSUE THREAD

**Issue by pabloqb** [OCA/OCB#861]
Impacted versions: 11.0

Current behavior: The [FIX] base, web: missing extension on binary downloads (5eb15c01b556620c77c0f7327494d4bf3117d115) adds an extension to the file even if the file already has one.

Expected behavior: Not add an extension if you already did it by code ?

Video/Screenshot link (optional): 
![added_extra_extension](https://user-images.githubusercontent.com/18447320/60906191-e26ac700-a276-11e9-823b-3c6e7e43bd7f.gif)

In the example of the video, a file containing `1|VAT|HOTELNAME|20190709|CODE|0` has `.pl` attached as extention

Hope this is of help,
Best regards,
Pablo

**Comment by pedrobaeza** [comment]
This is not the place for putting this, as this belongs to upstream odoo/odoo, but the problem you are commenting is already fixed. Update your sources.
