### ISSUE TITLE
[12.0] BUG in _on_login_cooldown

### ISSUE THREAD

**Issue by rodrig92** [OCA/OCB#864]
https://github.com/OCA/OCB/blob/07f4c81b3dd21b580fdb737c3918821c90e0aac7/odoo/addons/base/models/res_users.py#L837

The correct return value is False. "<login_cooldown_after>th (0 to disable)."

To reproduce:
Follow the instructions in the previous method "_assert_can_auth(self)":
"Login attempt ignored for %s on %s: "
                "%d failures since last success, last failure at %s. "
                "You can configure the number of login failures before a "
                "user is put on cooldown as well as the duration in the "
                "System Parameters. Disable this feature by setting "
                "\"base.login_cooldown_after\" to 0."

Put this value and enjoy...
You can't singin in Odoo

Regards.

**Comment by pedrobaeza** [comment]
This should be notified in odoo/odoo, not here.

**Comment by rodrig92** [comment]
Yes, my mistake.

I will do.

Thank you.
