### ISSUE TITLE
Send email in project task

### ISSUE THREAD

**Issue by JuaniFreedoo** [OCA/OCB#873]
Impacted versions: 12

Steps to reproduce:

1.- Create a project with email address
2.- Send an email to project address
3.- Odoo save the client address with this format in the email_from field : "Juan Ignacio Ubeda <juani@freedoo.es>"
4.- When you send an email with an action (manual or automated) Odoo send the email to juani@freedoo.es&gt 

juani@freedoo.es&gt    (juani@freedoo.es>) 

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is this specific of OCB?

**Comment by JuaniFreedoo** [comment]
I don't know Pedro,.... I'm going to try with Oficial Odoo repository

Thanks

**Comment by pedrobaeza** [comment]
OK, but be even more specific saying how do you define that "automated action", screenshots, etc.
