### ISSUE TITLE
How often are the sources synchronized with Odoo? 

### ISSUE THREAD

**Issue by lmignon** [OCA/OCB#875]
I need a patch for Odoo 10.0 integrated by Odoo on Friday and it is still not available in OCB...
https://github.com/odoo/odoo/commit/52526920085e94727ddc12d188af826ede7fd6d9

**Comment by pedrobaeza** [comment]
It's supposed to run daily on night, but I have also seen that 11.0 is not synchronized as well. Maybe a conflict. I'm trying manually now and tell you back. Responsible for this task in OCA board are your colleague @sbidoul (which is on holidays if I'm not wrong) and @gurneyalex.

**Comment by hbrunn** [comment]
it's supposed to happen every night, but because of

```
HEAD is now at 18af2b66341 Merge remote-tracking branch 'odoo/12.0' into 12.0
Fetching origin
Fetching odoo
From github.com:/odoo/odoo
   1a87fcc8a39..e64d2655c58  11.0              -> odoo/11.0
   b08a0025e79..f04f83545b7  12.0              -> odoo/12.0
   0a9bec8f186..5f1638e42de  saas-12.4         -> odoo/saas-12.4
   f6d56afba0e..af0d0dcf61d  saas-12.5         -> odoo/saas-12.5
 + 027679f42f6...f6416c5c5f6 staging.saas-12.5 -> odoo/staging.saas-12.5  (forced update)
   f6d56afba0e..b7b590a6400  tmp.saas-12.5     -> odoo/tmp.saas-12.5
Reset branch '12.0'
Branch 12.0 set up to track remote branch 12.0 from origin.
Your branch is up-to-date with 'origin/12.0'.
Already up-to-date.
Auto-merging doc/reference/testing.rst
Removing doc/reference/test-report.txt
Auto-merging doc/reference/cmdline.rst
CONFLICT (content): Merge conflict in doc/reference/cmdline.rst
Removing doc/reference/async.rst
Removing doc/python3.rst
Automatic merge failed; fix conflicts and then commit the result.
```

doesn't since the 13th. I don't have access to the machine running this any more (by accident? do I try to connect the wrong machine?) to fix this, but you can also manually propose a merge from 12 where you fix it, then the sync should go through again tonight.

**Comment by lmignon** [comment]
@pedrobaeza You're right Stephane is on holidays until the end of the week...

**Comment by pedrobaeza** [comment]
Done manually in https://github.com/OCA/OCB/commit/c87250f4735bed22af0552d46380ad030a9bcce3

Now doing the rest of the branches and solving conflict in 12.0.

It rests that @sbidoul or @gurneyalex check why this is not informed in Sentry and write a little README for allowing others like me to solve it.

@hbrunn which access are you trying?

**Comment by lmignon** [comment]
Thank you @pedrobaeza for the manual fix!

**Comment by pedrobaeza** [comment]
12.0 merge conflict manually solved in https://github.com/OCA/OCB/commit/db19e21ccbcc5ed1b3c1895a1390ac3e8cb83edc

Trivial solution, as it's an addition at the end of the paragraph. Curious any way why it hasn't been automatically solved, as no change in OCB has been made in that file.
