### ISSUE TITLE
11.0 Wrong calculation for field "to consume" when UOM of finished product is not BOM one

### ISSUE THREAD

**Issue by Lopsanz** [OCA/OCB#877]
Impacted versions: 
Seen at 11.0

Steps to reproduce:
Configure a BOM with UOM X
Make a manufacture order for a product with UOM Y
Clic on "Produce" 
Current behavior:
In the list of materials to consume, "To consume" fields multiplies production units with each units in BOM.

Expected behavior:
"To consume" fields must consider factor between UOM at BOM and at MO.

**Comment by pedrobaeza** [comment]
Hi, Sergio, as this something not specific to OCB, you have to publish your issue in odoo/odoo, not here.

**Comment by Lopsanz** [comment]
Ups! Sorry!

 

De: Pedro M. Baeza <notifications@github.com> 
Enviado el: martes, 24 de septiembre de 2019 12:00
Para: OCA/OCB <OCB@noreply.github.com>
CC: Sergio Lop Sanz <slop@sdi.es>; Author <author@noreply.github.com>
Asunto: Re: [OCA/OCB] 11.0 Wrong calculation for field "to consume" when UOM of finished product is not BOM one (#877)

 

Hi, Sergio, as this something not specific to OCB, you have to publish your issue in odoo/odoo, not here.
