### ISSUE TITLE
[11.0] unexpected behavior when sending a message

### ISSUE THREAD

**Issue by JorgeQuinteros** [OCA/OCB#886]
Impacted versions: 11.0
Steps to reproduce: 
When sending a message to a contact that does not have the email established and click on the "Discard" button.
Current behavior:
Even if we give the "Discard" button the contact is added as a follower automatically.
The same happens when we close the window without entering any email for the contact.
Expected behavior:
I understand that it is normal for the follower to be added automatically when we send a message, but I believe if we click on the button "Discard" or close the window, you should not add it as a follower.
Video/Screenshot link (optional):
When click on "Discard" button:
![Peek 08-11-2019 14-37](https://user-images.githubusercontent.com/43784849/68552386-c9d20f80-0416-11ea-91bb-1974197957c8.gif)
When close windows:
![Peek 08-11-2019 14-39](https://user-images.githubusercontent.com/43784849/68552398-dbb3b280-0416-11ea-8a2b-74ad69a797ee.gif)

**Comment by pedrobaeza** [comment]
Please put this issue in odoo/odoo, not here, as this is not something of OCB.
