### ISSUE TITLE
What is the policy for maintaining a branch up-to-date?

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/OCB#889]
I see that 12.0 and 13.0 branches are updated everyday with Odoo upstream, but 11.0 hasn't been updated for more than a month now (https://github.com/OCA/OCB/commits/11.0). Is it an OCA policy to only keep 2 versions up-to-date or is there any other problem going on?

**Comment by pedrobaeza** [comment]
No, it should be a conflict on the merge. cc @sbidoul @hbrunn @StefanRijnhart

**Comment by sbidoul** [comment]
It's in conflict since some time indeed. I'm adding @hbrunn @pedrobaeza in the notification list for OCB sync failure, since they are the two maintainer of this repo not yet in the list.

**Comment by pedrobaeza** [comment]
Yes, please.

**Comment by pedrobaeza** [comment]
I'm going to solve the conflict manually in local and push.

**Comment by pedrobaeza** [comment]
Conflicts solved and updated version uploaded.
