### ISSUE TITLE
[13.0] Print Bill in empty order

### ISSUE THREAD

**Issue by andrepurnomo** [OCA/OCB#892]
I'll try print bill in empty order and get this issue

Video/Screenshot link (optional):
![Screen Shot 2019-11-28 at 16 11 02](https://user-images.githubusercontent.com/24785523/69792733-bc2fce80-11f9-11ea-975a-602be17f8925.png)

**Comment by pedrobaeza** [comment]
Please open the issue in odoo/odoo instead of here, as this is not something specific of OCB, or is it? Any way, you should try to reproduce the problem in runbot and give all the steps to reproduce.
