### ISSUE TITLE
OCB missing documentation about OCB benefit

### ISSUE THREAD

**Issue by zeroheure** [OCA/OCB#896]
AFAIK, OCB purpose isn't documented anywhere. It should be on the OCA website.
I've found two threads that explain OCB benefit a bit, but are they still accurate ?

1. https://www.odoo.com/forum/help-1/question/odoo-v8-vs-saas-6-vs-ocb-v8-what-s-the-difference-58606 for the time Odoo wasn't very stable
1. https://odoo-community.org/groups/contributors-15/contributors-45694 "The future of OCB" on OCA list in 2016

Does it contains backports ?
Does it contains fixes that are not on same Odoo version, but on higher versions ?
Does it maintains versions that are no more maintained by Odoo ?
Why is it sometimes behind Odoo ? does it concern minor updates ?
Why should we use OCB instead of Odoo nightly ?

Thanks for yours answers.

**Comment by pedrobaeza** [comment]
Indeed some reference is needed. Thanks for bringing this recurrent topic. For me, a replace of the README in the main folder should be done with an explanation, although it's also indicated on OCA website. I will try to take a look to it.

**Comment by zeroheure** [comment]
AFAIK, there is nothing anymore about OCB on OCA website.

**Comment by zeroheure** [comment]
I've started an [OCB purpose FAQ in the wiki](/OCA/OCB/wiki/OCB-Purpose)

**Comment by zeroheure** [comment]
FAQ completed https://github.com/OCA/OCB/wiki/FAQ

**Comment by sbidoul** [comment]
Hi, a couple of comments about the FAQ:

1/ "The old runbot is using OCB to run, but runboat is not running on Odoo at all.". What does this mean ? runboat does use Odoo (via the [oca/oca-ci image](https://github.com/orgs/OCA/packages?repo_name=oca-ci)). We could change it to use OCB (it is configurable - although I personally prefer to use vanilla Odoo by default to make sure OCA addons do not depend on OCB specific changes).

2/ Should the CLA section mention the OCA CLA ?

**Comment by zeroheure** [comment]
@sbidoul Thanks, I will update Alexandre's answer. What is runboat ? is it the new runbot ?

> Should the CLA section mention the OCA CLA ?

of course

**Comment by sbidoul** [comment]
> What is runboat ? is it the new runbot ?

Yes, we are progressively replacing runbot. See [here](https://github.com/sbidoul/runboat), [here](https://twitter.com/SBidoul/status/1467143341083086864), [here](https://twitter.com/gurneyalex/status/1464315607822782469), and [here](https://twitter.com/SBidoul/status/1473056413840814083) if you want some reading ;)

You can find links in PR and commit statuses, such as these:

![image](https://user-images.githubusercontent.com/692075/147072855-9f460b36-cc82-4408-b18f-e4e0ef848c68.png)

**Comment by zeroheure** [comment]
@sbidoul FAQ updated with your answers. Many thanks.
