### ISSUE TITLE
Reports on Firefox

### ISSUE THREAD

**Issue by AquaMCU** [OCA/OCB#898]
Impacted versions: 13, Firefox 71.0 on Ubuntu 18.04

Steps to reproduce:
Open Report in FF. Chrome does not show the bug
![bug](https://user-images.githubusercontent.com/48280831/71352270-2d06a400-2576-11ea-8709-1ac4f2bd547c.gif)

Current behavior:
Reports are moving (see video)

Expected behavior:
Readable Report

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is OCB, not Odoo, so you only have to report things about specific problems in OCB, which is not the case. Try with latest version code and no custom addons in runbot, and if still happening, put the issue in odoo/odoo.
