### ISSUE TITLE
Invoice report totals' style needs fix

### ISSUE THREAD

**Issue by forvas** [OCA/OCB#902]
https://github.com/OCA/OCB/blob/a9a7834c8766246d3308eb09893f06a5b3639447/addons/account/views/report_invoice.xml#L134

The total lines of the invoice Qweb report are shown with too much line-height due to the following line:
```
<table class="table table-sm;page-break-inside: avoid;">
```
The class `table-sm` is being ignored because is mixed with a style.

The solution:
```
<table class="table table-sm" style="page-break-inside: avoid;">
```

Regards.

**Comment by pedrobaeza** [comment]
As this is not something specific of OCB, you should open the issue in odoo/odoo, not here, or even better, you can propose a pull request with that change. If Odoo doesn't accept the bugfix, then you can put the PR here for being integrated instead.

P.S.: You're not saying in which version. If it's <v11, then Odoo will reject it, as it's out of support.
