### ISSUE TITLE
[11.0] Error on commit 3903cf5, MRP module 'o_field_pdfviewer' class does not work

### ISSUE THREAD

**Issue by uolaizola** [OCA/OCB#921]
Impacted versions: 11.0

Steps to reproduce: 

1.- Create an empty database (check Load Demonstration data) 
2.- Install Manufacturing (mrp) module
3.- Go to settings -> General settings -> Manufacturing -> Check the option 'Work Orders & Quality'
3.- Go to Manufacturing menu -> Manufacturing orders -> MO/00003 -> click on 'Create Workorders'
4.- Go to Work Orders-> Open the MO/00003 - Table - Assembly Line 1 and open the 'Work instruction' tab

Current behavior:

The css rules 'o_field_pdfviewer' are not applied over the work instruction and the pdf is not correctly visualized, the image is small, the width and height are not as expected.

![pdf_mal](https://user-images.githubusercontent.com/44226087/78780663-430e6800-799f-11ea-91b5-f3151c2b9ac0.png)

Expected behavior:

The behavior previous of commit 3903cf5 where the height and witdth of  'o_field_pdfviewer' class are correctly applied and the work instruction is right. I consider that the changes of the commit are not supported in version 11.0 of Odoo. I think that it is not correct to incorporate an .scss file with sass format that is not supported, it causes and error and without assets the rules of the mrp.less file are not applied on the web browser

![pdf_bien](https://user-images.githubusercontent.com/44226087/78780904-a00a1e00-799f-11ea-9f05-f5fa02d255bc.png)
 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Put this in odoo/odoo instead of here, as this is not specific of OCB.
