### ISSUE TITLE
return PlanAction

### ISSUE THREAD

**Issue by miguelguldris** [OCA/OCB#941]
https://github.com/OCA/OCB/blob/6837849e14808aaad0fab4c5e0e05fe920d81363/addons/sale_timesheet/static/src/js/timesheet_plan.js#L235

I recently had to extend PlanAction functionality in a client module and I had to extend it from core.action_registry.get ('timesheet.plan');
Shouldn't PlanAction return here?

**Comment by pedrobaeza** [comment]
Well, this kind of changes are not accepted in Odoo in stable versions. You can try with a PR, but not here, in odoo/odoo.
