### ISSUE TITLE
Update of a record in a tree inside a form trigger reload of the form resetting current record position

### ISSUE THREAD

**Issue by sergiocorato** [OCA/OCB#943]
Impacted versions: 12.0

Steps to reproduce: Create a stock.picking with more than 40 stock.move

Current behavior: The page of stock moves inside the out is reset to first, instead of remaining where the user is working.

Expected behavior: The page is not reloaded

Video/Screenshot link (optional): 
![wh_out](https://user-images.githubusercontent.com/7657311/92596982-fbba3980-f2a6-11ea-8530-0ed04ac142a6.gif)

**Comment by pedrobaeza** [comment]
This should be in odoo/odoo, not here, as it's not something specific of OCB.

**Comment by sergiocorato** [comment]
moved to https://github.com/odoo/odoo/issues/57353
