### ISSUE TITLE
OCB 14.0 is not syncing

### ISSUE THREAD

**Issue by tsabi** [OCA/OCB#947]
Hi, i would like to ask when will be the 14.0 branch synced with odoo repository?

Thanks in advance,
Csaba

**Comment by pedrobaeza** [comment]
@sbidoul @gurneyalex did you do this?

**Comment by sbidoul** [comment]
@pedrobaeza not yet. I think you have access too, as well as @hbrunn, @StefanRijnhart.

**Comment by sbidoul** [comment]
I updated the sync script on the OCA server. See https://github.com/OCA/maintainer-tools/pull/473

**Comment by tsabi** [comment]
Thank you! :)
