### ISSUE TITLE
Production orders create internal picking without names

### ISSUE THREAD

**Issue by clonedagain** [OCA/OCB#95]
In OCB for some reason the internal picking code was changed from "stock.picking" to "stock.picking.internal".
This breaks the naming of pickings created by mrp because the change is not reflected in `_make_production_internal_shipment`.

**Comment by clonedagain** [comment]
Please flag "OCB regression".

**Comment by pedrobaeza** [comment]
Can you find when this was done?

**Comment by clonedagain** [comment]
git blame pointed me to f1295f158723fe72cac7b298b827f9f1dfd5c6ea . It looks like this as already prompted several patches, and looks related to https://github.com/odoo/odoo/issues/376

**Comment by pedrobaeza** [comment]
What we should do is to change this line https://github.com/OCA/OCB/blob/7.0/addons/mrp/mrp.py#L966 to point to `stock.picking.internal` code, because the other bug is also legitimate.

**Comment by pedrobaeza** [comment]
This line is also affected: https://github.com/OCA/OCB/blob/7.0/addons/stock/stock.py#L2127

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by clonedagain** [comment]
I closed my PR because I don't have a v7 instance anymore so I can't develop or test fixes.
Last I read was from @gurneyalex: "@StefanRijnhart I'm ok with undoing the initial fix, but we need some kind of migration script to update databases using this fix."

**Comment by pedrobaeza** [comment]
Closing as the PR was also dismissed by author.
