### ISSUE TITLE
On the pivot of the POS report, multiply quantities and amounts according to payment lines

### ISSUE THREAD

**Issue by anxoa77** [OCA/OCB#952]
Impacted versions: Odoo V13

Steps to reproduce: We create a pos order with two payment lines, in the Pivot report, it doubles the total price and the quantity

Current behavior: Double the quantity and total price on the pivot

Expected behavior: Do not multiply, according to the lines of the form of payment

Video/Screenshot link (optional): https://drive.google.com/file/d/1-tvLOOOTp4vp0d8jZVKrD0h6rASs5r_9/view

**Comment by pedrobaeza** [comment]
This is not something specific of OCB, so please report it in odoo/odoo.

**Comment by anxoa77** [comment]
Ok thanks Pedro
