### ISSUE TITLE
[14.0] User creation broken. 

### ISSUE THREAD

**Issue by codingforfun** [OCA/OCB#999]
User creation has been broken by 8dbd1efef899fb637acca3c318ae99cb23838b8f

Impacted versions: 14.0

Steps to reproduce:
Install 14.0 on an empty database and try to create a user. 

Current behavior:
Won’t create user due to mandatory field company not set. 

Expected behavior:
Should create user with the main company as before in 2d7f45e76607736bcc4f37bec480967ae2b373d7.

Also note the notable visual differences of the form before and after 8dbd1efef899fb637acca3c318ae99cb23838b8f.

**Comment by pedrobaeza** [comment]
Please put it in odoo/odoo, not here, as this is not something specific of this soft fork.

**Comment by codingforfun** [comment]
Ok. Sorry. Didn’t check this.
